### ISSUE TITLE
Input selection in ExtIO_RedPitaya_TRX.dll

### ISSUE THREAD

**Issue by Mat0ny** [pavel-demin/red-pitaya-notes#1012]
Hello Pavel,

the sdr_transceiver application starts servers for both inputs on ports 1001 and 1002. However, in ExtIO_RedPitaya_TRX.dll it is not possible to select a port for input selection. It would be great to add an input option.

Best regards and thanks
Matony

**Comment by pavel-demin** [comment]
Hello Matony,

If you want the ExtIO plug-in to connect to port 1002, then the easiest solution is to change the port number in the code and rebuild the plug-in.

I'm not really interested in changing the GUI part of this plug-in. If you really want to change it, then I'm afraid you will have to make the necessary changes.

Best regards,

Pavel
