### ISSUE TITLE
Help creating the SD card

### ISSUE THREAD

**Issue by Pricey42** [pavel-demin/red-pitaya-notes#1018]
### Description of the setup:

 * Device:  Red Pitaya 125-14
 * SD card image:  Example SD card from Red-Pitaya Notes
 * Application:  I am trying to setup the FT8 module for my PhD studies any help would be greatly appreciated
 * Other relevant information:

### Description of the problem:
I'm having trouble creating the sample SD card.  I've used dd to copy it to an 8Gb SD card but the Red-Pitaya will not boot from it.  I have the 125-14 device and I'm using a Mac to write the image.

**Comment by pavel-demin** [comment]
Please follow the getting started instructions from [this link](http://pavel-demin.github.io/red-pitaya-notes/alpine/#getting-started).

The micro SD card should be formatted as a freshly unpacked micro SD card (single partition, FAT32 file system). The files and directories from the zip file should be copied like normal files and directories without using special tools like `dd`.
