### ISSUE TITLE
Question on units

### ISSUE THREAD

**Issue by rus-ace** [pavel-demin/red-pitaya-notes#1021]
Dear Pavel:

Questions:

You wrote in one post that:
"The expression for the sample rate is 50000 / (rate + 5). The five are added so that the first five potentially noisy samples can be skipped."

### Description of the setup:

 * Device:
 * SD card image:
 * Application:
 * Other relevant information:

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment]
> are the units for this samples/second?

Yes, the units for the sample rate are samples per second.

> Also, can you explain why you chose a decimation rate for the vna of 2500.

When 2500 decimation rate is applied to 125 MSPS, the resulting sample rate is a nice round number (50000).

> Does this not throw out usable data, reducing signal/noise?

No, it does not throw out anything. The decimation is done by the CIC filter and signal/noise is higher after filtering/decimation.
