### ISSUE TITLE
GPS E1 E2 connector documents have changed at Red Pitaya website

### ISSUE THREAD

**Issue by waterwin** [pavel-demin/red-pitaya-notes#1023]
The PPS signal should be connected to the pin DIO3_N of the extension connector E1. The UART interface should be connected to the UART pins of the extension connector E2.

These links are outdated

They are now here:
Docs » 3. Developers guide » 3.1. Hardware » 3.1.1. Red Pitaya platforms » 3.1.1.2. STEMlab 125-14 » 3.1.1.2.5.1. Extension connector

**Comment by pavel-demin** [comment]
Thank you for finding this problem. I have updated the links with [this commit](https://github.com/pavel-demin/red-pitaya-notes/commit/6ee0d4f610a20b9ef2e3df5d8273d97627b54b16).

**Comment by waterwin** [comment]
Yes I copied your 5 corrections and it works again>
Thanks Pavel
    On Thursday, November 18, 2021, 08:19:04 PM GMT+1, Pavel Demin ***@***.***> wrote:  
 
 


Thank you for finding this problem. I have updated the links with this commit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
