### ISSUE TITLE
Feature request - include some version info in WSPR spots upload

### ISSUE THREAD

**Issue by dc1rdb** [pavel-demin/red-pitaya-notes#1027]
Hello Pavel, the wspr.rocks database is supporting version / source information of the uploaded spot data, see attached screenshot, last column.
Would it be possible to add something similar to the spot data uploaded from RedPitaya running your multiband WSPR transceiver software?
Thanks in advance for your consideration.
73 de Robert

![Screenshot_20211208-065000_Chrome](https://user-images.githubusercontent.com/9314230/145156780-da16b191-0369-4f6d-92fc-fda77a1fbe3a.jpg)

**Comment by pavel-demin** [comment]
Hello Robert,

I was recently informed that version information can be sent to wsprnet.org by adding `-F version=VERSION` to the curl command in [decode-wspr.sh](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_wspr/app/decode-wspr.sh#L65).

Best regards,

Pavel

**Comment by dc1rdb** [comment]
Great, thank you. Do you have any preference on how your software should identify itself?

**Comment by pavel-demin** [comment]
No, I do not have any preferences. Since this version field is optional and it is not used by wsprnet.org, I think you can fill it in with any information you want. I do not think it should be used to identify my software.

**Comment by dc1rdb** [comment]
Works perfect, thx!
