### ISSUE TITLE
ft8.cron links wrong

### ISSUE THREAD

**Issue by todkapuz** [pavel-demin/red-pitaya-notes#1028]
### Description of the setup:

 * Device: RP-125-14
 * SD card image:  red-pitaya-alpine-3.14-armv7-20211119
 * Application: ft8 transceiver
 * Other relevant information:

### Description of the problem:

the ft8.cron points to the wrong directory... points to "update-corr" directory, not "common_tools"

**Comment by pavel-demin** [comment]
Thank you for finding this problem. It is now fixed with [this commit](https://github.com/pavel-demin/red-pitaya-notes/commit/d006bc507ff0c7558745dd109cb1b04a6ae5dc73).
