### ISSUE TITLE
Document update GPS - FT8 / WSPR

### ISSUE THREAD

**Issue by waterwin** [pavel-demin/red-pitaya-notes#1029]
Since using common_tools as the dir for the update_corr script the documentation should be updated as well

1-59/2 * * * * cd /dev/shm && /media/mmcblk0p1/apps/common_tools/update-corr.sh >> update-corr.log 2>&1 &

to

1-59/2 * * * * cd /dev/shm && /media/mmcblk0p1/apps/common_tools/update-corr.sh 125 / 122.88>> update-corr.log 2>&1 &

to use the right base frequency for STEMlab  / SDRlab

**Comment by pavel-demin** [comment]
Thank you for finding this problem. I have updated the corresponding lines with [this commit](https://github.com/pavel-demin/red-pitaya-notes/commit/1852a87ba2e505f18bac7028b0b1742da31ae2c8).
