### ISSUE TITLE
make not found

### ISSUE THREAD

**Issue by df5sf** [pavel-demin/red-pitaya-notes#1031]
### Description of the setup:

 * Device: RedPitaya 122-16
 * SD card image: Alpine 20211119
 * Application: make gcc ....
 * Other relevant information:

### Description of the problem:
Hello,
after installing make, gcc and other stuff with
apk add build-base gcc abuild binutils binutils-doc gcc-doc cmake cmake-doc extra-cmake-modules extra-cmake-modules-doc
all works fine. I can compile  sdr-transceiver-hpsdr.c
But after reboot or shutdown I get the error: -ash: make: not found
After a new apk add build-base gcc abuild bi .... it works.

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment]
Here is the command that saves the configuration changes to SD card:
```
lbu commit -d
```

More information on why it works this way and what the `lbu` command does can be found at the following links: 
https://wiki.alpinelinux.org/wiki/Installation#Diskless_Mode
https://wiki.alpinelinux.org/wiki/Alpine_local_backup
