### ISSUE TITLE
How can I recompile the write-c2-files.c to be used in the alpine environment - Question

### ISSUE THREAD

**Issue by waterwin** [pavel-demin/red-pitaya-notes#1032]
Dear Pavel and all,
I would like to do some experiments by changing the write-c2-files.c.
How can I recompile the file so it can be used again on the Red Pitaya in the Alpine Linux environment?

Thanks for any suggestions,
Erwin

**Comment by pavel-demin** [comment]
Dear Erwin,

I think the easiest would be to compile `write-c2-files.c` directly on the Red Pitaya board. At least, that is how I do when I need to test some changes.

The necessary tools can be installed with the following command:
```
apk add make gcc
```
If you prefer to keep them installed by default, then write the changes to the SD card with the following command:
```
lbu commit -d 
```
The commands to compile `write-c2-files.c` are
```
cd apps/sdr_transceiver_ft8
rw
make
```
Best regards,

Pavel
