### ISSUE TITLE
How can I use the SDR transceiver, GPIOs and UART?

### ISSUE THREAD

**Issue by up201605771** [pavel-demin/red-pitaya-notes#1041]
### Description of the setup:

 * Device: Red Pitaya 125-14
 * SD card image: [v1.04-25](https://github.com/RedPitaya/RedPitaya/releases/tag/v1.04-25)
 * Application: sdr-transceiver
 * Other relevant information: I have downloaded the application through redpitaya bazzar

### Description of the problem:
Dear Pavel,

My project consists of using the redpitaya as an SDR and at the same time being able to use the redpitaya GPIOs and UART interface.
I understand the SDR Transceiver fpga image is different from the one provided on the RedPitaya website and therefore I cannot use the C API functions along with your fpga image. Ideally I wanted to use the C API, as all the developed code used this...

I want to have RF communication and digital communication, and the communication devices power are controlled by the redpitaya GPIOs, but I can't see a way of doing it. Does your FPGA image allow access to gpios as well as UART? If so, where can I find that information/examples or how can I do it?

Also, is there any project that combines an SDR with the C API?

Thank you in advance!

**Comment by up201605771** [comment]
Thank you for your quick answer.

> Have you considered using the [SDR transceiver compatible with HPSDR](http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr)? This application has all the GPIO pins enabled, UART communication and more features when using additional modules (audio codec, GPIO extensions, etc.).

- No I did not. I was wondering if it is compatible with gnuradio the same way as is the SDR transceiver. My idea is to first create a program that "dumps" a signal to TX  with information and receive it (RX). This signal is modulated/demodulated in frequency using the OFDM transmitter/receiver block of gnuradio where the carrier is at 60KHz.  For example, redpitaya 1 transmits "hello world" and redpitaya 2 receives/demodulates and prints on the terminal "hello world".

- When you say it has all the GPIO pins enabled, it means I can write/read them the same way the C API does? Or their memory position is different? Do you have any example?

> There is nothing specific to using the UART port on the Red Pitaya board. Its use does not require the Red Pitaya API. Here is an example provided by Red Pitaya that does not use their API: https://github.com/RedPitaya/RedPitaya/blob/master/Examples/C/uart.c

- Ok, thank you very much for the answer

**Comment by pavel-demin** [comment]
> Do you have any example?

Yes it is in the source code of this application:

https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c

The code for GPIO and UART can be found by searching for "gpio" and "uart".

**Comment by up201605771** [comment]
Hello again,

I managed to install the [SDR transceiver compatible with HPSDR](http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr). 

I just have one more question maybe you can guide me in the right direction. 

I installed the [gr-hpsdr](https://github.com/Tom-McDermott/gr-hpsdr) in redpitaya and run the [sdr-transceiver-hpsdr](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c) according to your notes (previous to this, I updated the fpga image which I have downloaded from the bazaar). I am trying a simple example of generating a sine wave from OUT1 and receiving it in IN1 but with no luck. The GUI opens, but no signal is displayed.

![image](https://user-images.githubusercontent.com/47570190/161749810-c5429c29-f814-43dd-8d3b-34fc1643da33.png)
I believe I have made some(s) mistake(s) in configuring the block. Do you happen to know how should I configure it, in order to see the signal in IN1? Reading some previous questions made to you I understood the Redpitaya Sink/Source will not work with  [sdr-transceiver-hpsdr](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c) 

Thank you.

**Comment by pavel-demin** [comment]
You did not mention that using GNU Radio is a requirement.

If your project requires GNU Radio, then it would be probably better to return to your initial solution and continue using the SDR transceiver application.

GPIO pins in the SDR transceiver application can be enabled similarly to how it is done in the commits at the following link:
https://github.com/f5mzn/red-pitaya-notes/commits/master
