### ISSUE TITLE
Question about FPGA

### ISSUE THREAD

**Issue by davidhay45** [pavel-demin/red-pitaya-notes#1050]
sdr_transceiver_wspr_122_88 project

I wanted to add an input gpio pin to the bit stream file used by this project.  In order to do this I brought the common_tools/block_design.tcl inline and added a debouncer for pins DIO0_N to DIO3_N intending to use DIO0_N as my new input gpio.  However to make this work I had to remove the "PPS" and "Level Measurement" sections as they also use the same pins.  If I need to use the measure-level and measure-corr programs I can use the original bit stream.

However, is it possible to program the fpga to use DIO3_N for its original purpose and use DIO0_N for gpio?

I realise that asking this question here is off-topic but I don't know where else to ask.

Thanks

David

**Comment by pavel-demin** [comment]
If I remember correctly only DIO3_N is used and all other DIO*_N pins are not used in this project.

I do not use GPIO pins much in my projects. I think only the [sdr_transceiver_hpsdr](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/sdr_transceiver_hpsdr) project uses all the pins. So, maybe you could find some useful examples there.

I think the answer to your question is yes. The FPGA can most likely be programmed to use the pins according to your requirements.
