### ISSUE TITLE
Question: Is there a way to detect the TUNE button pressed

### ISSUE THREAD

**Issue by davidhay45** [pavel-demin/red-pitaya-notes#1053]
I am using a Redpitaya 122-16 with the latest Alpine sd card image (red-pitaya-alpine-3.14-armv7-20220322) and running HPSDR from PowerSDR mRX PS v3.4.7 under Windows 10.  Is there any way to detect in sdr_transceiver_hpsdr.c when the TUN button has been pressed, as opposed to normal PTT (MOX button)?

I have an AT100 which I am controlling via I2C and want to trigger the tune sequence automatically.

Thanks

**Comment by pavel-demin** [comment]
I do not think that it is possible to detect TUNE mode in sdr_transceiver_hpsdr.c.
