### ISSUE TITLE
/dev/cma open error while running adc-test/server 

### ISSUE THREAD

**Issue by glnmurthy** [pavel-demin/red-pitaya-notes#1056]
Hi Pavel,
Iam trying to run adc-test on redpitaya 125. 
I could compile both client and server programs.
But while running server program, I got /dev/cma Open error
I could find /dev/mem, but /dev/cma not there.
Can you please suggest what to do

**Comment by pavel-demin** [comment]
What SD card image are you using?

Normally, the latest version of the SD card image from this repository ([red-pitaya-alpine-3.14-armv7-20220322.zip](https://github.com/pavel-demin/red-pitaya-notes/releases/download/20220322/red-pitaya-alpine-3.14-armv7-20220322.zip)) contains /dev/cma.

**Comment by pavel-demin** [comment]
Here is the additional information from #1057:

 * Device: redpitaya 125-10
 * SD card image: supplied by Redpitaya
 * Application: ADC Test for 125Msps

**Comment by pavel-demin** [comment]
The projects in this repository that use the CMA driver and `/dev/cma` work with SD card images from this repository.

The source code of the driver is in [patches/cma.c](https://github.com/pavel-demin/red-pitaya-notes/blob/master/patches/cma.c). I think it should be possible to add this driver to the SD card image provided by Red Pitaya. However, I think that it would be much easier to use an SD card image from this repository.

Additionally, projects in this repository are only tested with STEMlab 125-14 and STEMlab 122.88-16 SDR. To work with STEMlab 125-10 they would probably have to be modified. Some information about the modifications can be found in #1052.

**Comment by glnmurthy** [comment]
I am using the same
