### ISSUE TITLE
Build environment setup requires x windows, not in mini.iso install (Solved)

### ISSUE THREAD

**Issue by mgarrett1955** [pavel-demin/red-pitaya-notes#1068]
First, thank you for the awesome work!!

I need to create a program based on the sdr_tranceiver example. My application requires
the SDR functionality as implemented in the FPGA (I do not need to change the FPGA code,, yet..)

The environment on the RedPitaya does not have the build tools for the .c application.

I assume that I need the build environment to build the application. 

Is there a reference that shows how to build the code and get it into the SD card image?

Thank you in advance!

### Description of the setup:

 * Device:
 * RedPitaya build environment
 * SD card image:
 * N/A
 * Application:
 * Setup of Xilinx build environment requires x windows
 * Other relevant information:
 * Setting up the build environement on a Win10 Machine

### Description of the problem:
I installed Virtual box and the mini.iso, using the boot script provided in the instructions
I can SSH into the machine
I downloaded the Xilinx environment on the Win10 Machine
Using scp, i transfere it to /home/red-pitaya
I switched to the root user
I un tarred the .tar.gz file in /home/red-pitaya
I created /opt/Xilinx directory
When I run ./xsetup I get the following error:
Error: Installer could not be started
No X!! DISPLAY variable was set, but the program performed an operation that required it.
Java.Headless Exception.......

Do I need an xterminal running?

**Comment by mgarrett1955** [comment]
I found an xserver for Windows 10 call X410. I then used Putty to log into the session, with X11 forwarding turned on and it worked!!

**Comment by pavel-demin** [comment]
> The environment on the RedPitaya does not have the build tools for the .c application.

I think the easiest would be to compile `sdr_tranceiver` directly on the Red Pitaya board. At least, that is how I do when I need to test some changes.

The build tools can be installed with the following command:
```
apk add make gcc
```
If you prefer to keep them installed by default, then write the changes to the SD card with the following command:
```
lbu commit -d 
```
The commands to compile `sdr_tranceiver` are
```
cd apps/sdr_tranceiver
rw
make
```

**Comment by mgarrett1955** [comment]
Pavel,

That will work perfect! I will set that up today.

Thank you!
