### ISSUE TITLE
Vivado 2022.1 open project with TCL Command (xbip_dsp48_macro error)

### ISSUE THREAD

**Issue by ByoungjinKim** [pavel-demin/red-pitaya-notes#1070]
Hello.

I'm using Vivado 2022.1. I try this project in this version. But I'm not open project.

The address below was used as a reference..
https://github.com/pavel-demin/red-pitaya-notes/issues/1058

sdr_transceiver_122_88 : build ok
sdr_transceiver_emb_122_88 : error

![image](https://user-images.githubusercontent.com/97871682/210024493-0b39b490-2b1b-4aee-a738-bd4738e633ab.png)

how can i fix it?

**Comment by pavel-demin** [comment]
I think that the easiest workaround at the moment is to use Vivado 2020.2.

Xilinx has removed the DSP48 macro (xbip_dsp48_macro) from Vivado 2021.1 and newer versions.

The new DSP macro has some issues that the DSP48 macro does not.

I have posted a description of these issues on the Xilinx forum:

https://support.xilinx.com/s/question/0D52E00006iHpkX

**Comment by ByoungjinKim** [comment]
thank you

**Comment by pavel-demin** [comment]
I have replaced `xbip_dsp48_macro` with [dsp48](https://github.com/pavel-demin/red-pitaya-notes/blob/master/cores/dsp48_v1_0/dsp48.v) in all projects. I think that it should now be possible to build all projects with Vivado 2022.1.

**Comment by ByoungjinKim** [comment]
build test OK.
Thank you.
