### ISSUE TITLE
How change Alpine Linux IP ?

### ISSUE THREAD

**Issue by ByoungjinKim** [pavel-demin/red-pitaya-notes#1071]
Communication is not working, so I want to change the IP.

SDRlab board - router - PC : not Ping

SDRlab - PC (direct connect) : Ping OK

i guess gateway problem. so i want change ip.

I connected it to the linux on board via USB.

vi /etc/dhcpcd.conf

change ip address, and then reboot

The ip is not changed, and the modified file is restored.

How can I do it?

![image](https://user-images.githubusercontent.com/97871682/210209161-f6470a93-6ace-4733-9532-38c689bf6dd6.png)

**Comment by pavel-demin** [comment]
You are almost there.

You need to run the following command to save the configuration changes to the SD card:
```
lbu commit -d
```

**Comment by ByoungjinKim** [comment]
> You are almost there.
> 
> You need to run the following command to save the configuration changes to the SD card:
> 
> ```
> lbu commit -d
> ```

thank you
ip change OK
but, not operating.
I think it's because of security in the company.
direct link is ok
