### ISSUE TITLE
SDR#, GNU radio not operating, How can i fix it?

### ISSUE THREAD

**Issue by ByoungjinKim** [pavel-demin/red-pitaya-notes#1072]
HDSDR : OK

SDR# program : no source list
- copyed put ExtIO_RedPitaya_122_88.dll in SDR# folder, but it is not in the source list.

![image](https://user-images.githubusercontent.com/97871682/210286849-4785d63b-f4ba-4e3a-b825-0998dbeb1c8d.png)

GNU radio program
- There is an error, can't start
![image](https://user-images.githubusercontent.com/97871682/210286874-fb3d9c15-0635-4970-b733-34216c164e3f.png)

how can i fix it?

thank you

**Comment by ByoungjinKim** [comment]
The GNU radio program identified the problem.
It is not registered in the environment variable.
So in \radioconda\Library\share\gnuradio\grc\blocks folder
After copying .xml and .yml, the error disappeared.

But I don't know about SDR# yet.

**Comment by pavel-demin** [comment]
Looking at the SDR# screenshot, I would say that you are not using the SDR# version linked from my notes. As far as I know, newer versions of SDR# do not support ExtIO plugins.

The provided GNU Radio examples only work on Linux.

**Comment by ByoungjinKim** [comment]
sorry. Didn't check the version.
Does it only work on Linux?
Um... Then I'll have to make a new Windows version.
Okay. thank you
