### ISSUE TITLE
Synchronization of two STEMlab 125-14 via SATA daisy chain

### ISSUE THREAD

**Issue by popovkon** [pavel-demin/red-pitaya-notes#1073]
### Description of the setup:

 * Device: STEMlab 125-14
 * SD card image: Debian Linux
 * Application: generation of 10MHz sinewave at DAC outputs
 * Other relevant information: 

### Description of the problem:
Dear Pavel,

I am a Ph.D. student in SOKENDAI university, Japan.
I have developed Low-Level RF feedback to stabilize phase and amplitude for LUCX accelerator RF-Gun.
LUCX accelerator is a linear electron accelerator. I attach URL of the paper with the facility description.

https://accelconf.web.cern.ch/ipac2022/papers/tupopt066.pdf

I used your projects and FPGA images for the feedback development.

So far, I must synchronize DAC outputs of two STEMlab 125-14 boards via SATA connection.
To the best of my knowledge, it is called "SATA daisy chain".

1) How to synchronize Clocking Wizard (PLL) with clock signal sent via SATA? Please, see picture below

![Clocking_wizard_PLL](https://user-images.githubusercontent.com/105579416/210546945-adfb495e-53e5-47e3-9f2c-4965082697ed.png)

2) Could you advice me how to synchronize two FPGA boards' DAC outputs using these outputs and inputs?
![SATA_ports](https://user-images.githubusercontent.com/105579416/210547458-ad9673e9-1005-4210-af57-553a88766ed4.png)

3) How do these inputs and outputs work?

Thank you in advance!

Sincerely,
Popov Konstantin

**Comment by pavel-demin** [comment]
Hello Konstantin,

If I understand correctly the idea of the Red Pitaya developers, then they currently propose the following clocking configuration:
- master board outputs clock and trigger signals to both SATA connectors
- slave boards receive clock and trigger signals from master and output this clock from FPGA to ADC and DAC
- slave boards should have the resistors R25 and R26 removed and resistors R27 and R28 installed as shown on page 3 of the schematics

I have just added to this repository the following two projects that I used to test this clocking configuration:

https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/led_blinker_master
https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/led_blinker_slave

**Comment by popovkon** [comment]
Dear Pavel, 
Thank you very much for your response!

Just to be sure,
If I change the resistors' positions and apply "led_blinker_master" and "led_blinker_slave" clocking configuration,
slave STEMlab 125-14 FPGA board will be locked with master board clock. I mean DAC outputs and ADC inputs.
Is it so?


Sincerely,
Konstantin

**Comment by pavel-demin** [comment]
Yes, it is more or less so.

There are, however, a few problems:
- the distribution of clocks via FPGA brings additional jitter
- sending 125 MHz clock through SATA cables does not seem very reliable
- the phase of the clock on the slave board must be adjusted to compensate for phase shift due to SATA cables and other elements in the path of the clock

If you only need to use DAC outputs, this can be done without changing the resistors. Resistors configure the clock input of the ADC chip. The DAC chip is always clocked from the FPGA.

**Comment by popovkon** [comment]
Thank you!

OK. I understand.
So far, I need only DAC outputs at both STEMlab 125-14 boards.
I will try to phase-lock DAC outputs using SATA today.

I will update the information about this issue today.

Sincerely,
Konstantin

**Comment by popovkon** [comment]
Good evening, Pavel!

I have tried the following configuration for the slave board. Please, check the picture bellow.
![Screenshot from 2023-01-06 00-35-28](https://user-images.githubusercontent.com/105579416/210805905-47d3d73e-e5db-4d4a-bdba-7bb41100c5ab.png)

I supplied "daisy_clock_n_i" and "daisy_clock_p_i" into Clocking wizard.
![Screenshot from 2023-01-06 00-39-47](https://user-images.githubusercontent.com/105579416/210806677-8d30041f-2cc0-4517-9105-827e65b92c33.png)
![Screenshot from 2023-01-06 00-39-50](https://user-images.githubusercontent.com/105579416/210806719-49d6ea18-0379-4fe6-be17-32ed86cbb545.png)

Then, I supplied 3 clocks with "locked" signal to the DAC.


It does not work. Vivado shows error. I attach error screenshot.

![Screenshot from 2023-01-06 00-34-22](https://user-images.githubusercontent.com/105579416/210807537-305bf663-b123-41bc-9aa5-7bff8fa79d63.png)
![Screenshot from 2023-01-06 00-31-00](https://user-images.githubusercontent.com/105579416/210807775-75a33667-6e77-4f14-b3ee-4da19f511f26.png)

I do not understand what is wrong. Could you advice me how to solve this problem?

Sincerely,
Konstantin

**Comment by popovkon** [comment]
I have some ideas. I will try to figure what is wrong.

**Comment by pavel-demin** [comment]
I can build bitstream for the following configuration:
```
# SATA connectors

delete_bd_objs [get_bd_ports adc_enc_p_o]
delete_bd_objs [get_bd_ports adc_enc_n_o]

create_bd_port -dir I daisy_trg_p_i
create_bd_port -dir I daisy_trg_n_i

create_bd_port -dir I daisy_clk_p_i
create_bd_port -dir I daisy_clk_n_i

create_bd_port -dir O daisy_trg_p_o
create_bd_port -dir O daisy_trg_n_o

create_bd_port -dir O daisy_clk_p_o
create_bd_port -dir O daisy_clk_n_o

create_bd_port -dir O adc_clk_p_o
create_bd_port -dir O adc_clk_n_o

# Create clk_wiz
cell xilinx.com:ip:clk_wiz pll_0 {
  PRIMITIVE PLL
  PRIM_IN_FREQ.VALUE_SRC USER
  PRIM_IN_FREQ 125.0
  PRIM_SOURCE Differential_clock_capable_pin
  CLKOUT1_USED true
  CLKOUT1_REQUESTED_OUT_FREQ 125.0
  USE_RESET false
} {
  clk_in1_p daisy_clk_p_i
  clk_in1_n daisy_clk_n_i
}

# Create processing_system7
cell xilinx.com:ip:processing_system7 ps_0 {
  PCW_IMPORT_BOARD_PRESET cfg/red_pitaya.xml
} {
  M_AXI_GP0_ACLK pll_0/clk_out1
}

# Create all required interconnections
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 -config {
  make_external {FIXED_IO, DDR}
  Master Disable
  Slave Disable
} [get_bd_cells ps_0]

# Create xlconstant
cell xilinx.com:ip:xlconstant const_0

# Create util_ds_buf
cell xilinx.com:ip:util_ds_buf:2.1 trg_buf_0 {
  C_SIZE 1
  C_BUF_TYPE OBUFDS
} {
  OBUF_DS_P daisy_trg_p_o
  OBUF_DS_N daisy_trg_n_o
  OBUF_IN const_0/dout
}

# Create util_ds_buf
cell xilinx.com:ip:util_ds_buf:2.1 trg_buf_1 {
  C_SIZE 1
  C_BUF_TYPE IBUFDS
} {
  IBUF_DS_P daisy_trg_p_i
  IBUF_DS_N daisy_trg_n_i
}

# Create util_ds_buf
cell xilinx.com:ip:util_ds_buf:2.1 clk_buf_0 {
  C_SIZE 1
  C_BUF_TYPE OBUFDS
} {
  OBUF_DS_P daisy_clk_p_o
  OBUF_DS_N daisy_clk_n_o
  OBUF_IN const_0/dout
}

# Create util_ds_buf
cell xilinx.com:ip:util_ds_buf:2.1 clk_buf_1 {
  C_SIZE 1
  C_BUF_TYPE OBUFDS
} {
  OBUF_DS_P adc_clk_p_o
  OBUF_DS_N adc_clk_n_o
  OBUF_IN const_0/dout
}

# LED

# Create c_counter_binary
cell xilinx.com:ip:c_counter_binary cntr_0 {
  Output_Width 32
} {
  CLK pll_0/clk_out1
}

# Create port_slicer
cell pavel-demin:user:port_slicer slice_0 {
  DIN_WIDTH 32 DIN_FROM 26 DIN_TO 26
} {
  din cntr_0/Q
  dout led_o
}
```

**Comment by popovkon** [comment]
Hello, Pavel!

Thank you!
I understand the configuration.
I am trying this configuration right now.
I will tell the results soon.

Sincerely,
Konstantin

**Comment by popovkon** [comment]
Dear Pavel,

Good afternoon!
I tried your configuration. It works well.
Here is the configuration of master board.
![Screenshot from 2023-01-07 22-02-03](https://user-images.githubusercontent.com/105579416/211149827-87862e6a-f2b4-4748-a426-1e53d27b3e39.png)

Here is slave board.
![Screenshot from 2023-01-07 22-03-31](https://user-images.githubusercontent.com/105579416/211149878-c388af20-2089-4324-b780-b7903a1e3eba.png)

Here is picture of FPGA boards connection via SATA.
![IMG_20230107_205356](https://user-images.githubusercontent.com/105579416/211150142-1ca3cf5c-7157-411b-b408-d1e84315cad3.jpg)

DAC outputs of both FPGA boards are phase-locked. There is not phase drift. So, I attach screenshots from oscilloscope.
10MHz signals screenshot is bellow.
![Phase_stability_between_2_FPGA_boards_via_SATA](https://user-images.githubusercontent.com/105579416/211149938-273674f9-f1b8-4bbc-a121-b233467ca8a8.jpg)

40MHz signal is bellow.
![Phase_stability_between_2_FPGA_boards_via_SATA_40MHz_output](https://user-images.githubusercontent.com/105579416/211149965-97a64cd3-1798-4214-9d02-58ccd1dc0761.jpg)

Thank you very much for your help!
Spasibo!

Sincerely,
Popov Konstantin
