### ISSUE TITLE
STEMlab 125-14 as phase coherent Lidar system

### ISSUE THREAD

**Issue by nsparks-per** [pavel-demin/red-pitaya-notes#1074]
### Description of the setup:

 * Device: STEMLab 125-14
 * SD card image: Alpine 3.14-arm7-20220322
 * Application: Phase Coherent LIDAR system

### Description of the problem:

Hello,

I'm developing a LIDAR system based on the STEMlab 125-14 platform. For this, I want to output the same waveform on both outputs of the red pitaya and then read them using both analog inputs. The issue is there is a different phase shift each time I start the process. I've tracked at least one issue down to the two output channels not having a consistent starting phase offset. This setup is shown below.
![image](https://user-images.githubusercontent.com/73674830/212945355-d70ea7fd-5716-4939-9d1c-8176cd221ba4.png)

I've modified the SDR-Transceiver code to reset and then load both transmit channels using the following method. The data loaded into the two buffers should be the same.

```
void *txboth_data_handler(void *arg)
{
  //printf("TX Handler: start TX handler\n");
  
  int i, chan1, chan2, sock_client1 = sock_thread1[6], sock_client2 = sock_thread1[7];
  uint64_t buffer1[2048], buffer2[2048];
  //printf("TX Handler: Reset both channels\n");

  
  *tx_rst1 |= 1;
  *tx_rst2 |= 1;
  *tx_rst1 &= ~1;
  *tx_rst2 &= ~1;
  
  while(1)
  {
    //printf("TX Handler: Checking if buffer is over 4096\n");
    while(*tx_cntr1 > 4096 || *tx_cntr2 > 4096) usleep(500);

    if(*tx_cntr1 == 0 && *tx_cntr2 == 0)
    {
      for(i = 0; i < 2048; ++i)
      {
        *tx_data1 = 0;
        *tx_data2 = 0;
      } 
    }

    chan1 = recv(sock_client1, buffer1, 16384, 0);
    chan2 = recv(sock_client2, buffer2, 16384, 0);

    //printf("Chan 1:%d Chan 2:%d\n", chan1, chan2);

    //printf("TX Handler: Receiving data\n");
    if(chan1 <= 0) break;
    if(chan2 <= 0) break;

    //printf("TX Handler: Loading data to buffer\n");
    for(i = 0; i < 2048; ++i)
    {
      *tx_data1 = buffer1[i];
      *tx_data2 = buffer1[i];
    }
  }
  
  close(sock_client1);
  close(sock_client2);
  sock_thread1[6] = -1;
  sock_thread1[7] = -1;
  
  return NULL;
}
```
I realized one possible source of the random phase difference is the two output buffers not being reset at the same time. This led me to modify the FPGA image so the RX channels and TX channels share common reset bits.

![image](https://user-images.githubusercontent.com/73674830/212949723-f45b0b22-fed4-49ea-8fad-1d0602420bb1.png)

![image](https://user-images.githubusercontent.com/73674830/212950094-dbe8be2b-48dc-47cf-a1ef-409152357e93.png)

![image](https://user-images.githubusercontent.com/73674830/212950317-0b48d93c-4137-44e9-b0a0-8db46df35a29.png)

After building and loading the new .bit file to the red pitaya and using the new C program I run GNU radio to start the transmit channels and then measured the phase difference using a moku go mobile oscilloscope. GNU radio created a 1 MHz sine wave with a sample rate of 50k. The resulting waveform outputs are shown below.

First start
![image](https://user-images.githubusercontent.com/73674830/212953548-fe615a06-2ed4-4a3c-95c5-057797aeeacc.png)

Second start
![image](https://user-images.githubusercontent.com/73674830/212954200-22a30bbc-3afc-4660-bd2b-b53cc8cfa3b6.png)

Third start
![image](https://user-images.githubusercontent.com/73674830/212954507-f93f44e0-115c-4668-a3aa-a9f79e92bd66.png)

I decided to take a single shot of both channels starting up and there is a noticeable time delay between the two. 

Single shot
![image](https://user-images.githubusercontent.com/73674830/212955814-d5c95d13-368e-4a3f-bca0-b62fb2ad96b8.png)

Do you have any suggestions on how I can make this time delay consistent? As long as there is a consistent phase delay I can account for it but the random phase delay would require calibration each time I start the program.

Thanks

**Comment by pavel-demin** [comment]
What you observe is normal behavior of the SDR transceiver application. The two transceivers in this application are completely independent and were never designed to work synchronously.

I think that among the applications in this repository, the closest match to your requirements would be the [Vector Network Analyzer](http://pavel-demin.github.io/red-pitaya-notes/vna/) application.
