### ISSUE TITLE
increasing sample rate in gnu radio block

### ISSUE THREAD

**Issue by otpisani** [pavel-demin/red-pitaya-notes#1076]
### Description of the setup:

 * Device:
 * SD card image:
 * Application:
 * Other relevant information:

Application

### Description of the problem:

Increase sample rate for sdr-tranciever or wide-tranciever

### Steps to reproduce the problem:

 1. Don't know if it's possible to increase samples in sdr-tranciever for double at least, up to 2.5MS/S for gnu radio block, which would also work of course for wide-tranciever
 2. Is it doable to change code with vivado programing FPGA
 3. If yes, can you point me to the source

**Comment by pavel-demin** [comment]
No, it is not possible.
