### ISSUE TITLE
Building a bootable SD card image: fails by missing programms

### ISSUE THREAD

**Issue by waterwin** [pavel-demin/red-pitaya-notes#1083]
sudo sh scripts/image.sh scripts/debian.sh red-pitaya-debian-11.3-armhf.img 1024 fails

missing are:
```
parted
losetup
mkfs.vfat
mkfs.ext4
debootstrap
depmod
zerofree
```
They are not in the list of pre-reqs
From Pre-requirements
```
sudo apt-get --no-install-recommends install \
  bc binfmt-support bison build-essential ca-certificates curl \
  debootstrap device-tree-compiler dosfstools flex fontconfig git \
  libgtk-3-0 libncurses-dev libssl-dev libtinfo5 parted qemu-user-static \
  squashfs-tools sudo u-boot-tools x11-utils xvfb zerofree zip
```
They are partially in a list from Issue #  that also overlaps incompletely with the Pre-req list
```
sudo apt-get install \
  build-essential bison flex git curl ca-certificates sudo \
  xvfb fontconfig libxrender1 libxtst6 libxi6 lib32ncurses5 \
  bc u-boot-tools device-tree-compiler libncurses5-dev \
  libssl-dev qemu-user-static binfmt-support zip \
  squashfs-tools dosfstools parted debootstrap zerofree
```
My environment : Debian 11.6 with GUI instead of the Debian 11.3 from the mini.iso (I doubt that explains it) in VirtualBox on Windows 10

I will run the list from the Issue and retry, when needed after installing other missing parts manually

**Comment by pavel-demin** [comment]
> you can not run a command to install sudo with the command sudo

Thanks. I have updated the notes and removed `sudo` from the `apt-get` commands.

**Comment by waterwin** [comment]
libtinfo5needs to be installed before Vitis will install, this is a known Vitis issue, if not it will hang indefinitely on the action " Generating installed device list"
So this pre-req is in fact for the page before : Setup Development Machine / 
Installing Vitis Core Development Kit

Thanks Pavel, as always.
ErwinPE3ES / F4VTQ
    On Wednesday, March 1, 2023 at 07:58:20 PM GMT+1, Pavel Demin ***@***.***> wrote:  
 
 



you can not run a command to install sudo with the command sudo


Thanks. I have updated the notes and removed sudo from the apt-get commands.

**Comment by pavel-demin** [comment]
All these packages are installed by the [debian.seed](https://github.com/pavel-demin/red-pitaya-notes/blob/gh-pages/etc/debian.seed) script used to automatically create a virtual machine in the Development Machine notes.
