### ISSUE TITLE
Feature Request - TRX-DUO 16Bit ADC

### ISSUE THREAD

**Issue by enthru** [pavel-demin/red-pitaya-notes#1088]
Hello Pavel!

As i understand correctly the main difference between 16bit Red Pitaya and TRX-DUO (chinese clone of 16 bit Red Pitaya, but with 125MHz clock and maybe some other differences) is in different clock frequencies.
Can i ask you about possibility to modify FPGA code to be able to use 16bits of data on TRX-DUO?

I've made an attempt trying to use 122.88 clock but ext.clock ("short:ext.clock" ) jumper didn't worked as expected (no result when short, still uses internal clock). So looks like i need to desolder old generator first, but anyway maybe it will be useful for somebody who can't solder new generator (maybe replacing clock is not going to work at all).

**Comment by pavel-demin** [comment]
The main difference between these two boards for me is the size of the FPGA (XC7Z010 vs XC7Z020) . The XC7Z020 FPGA on the Red Pitaya SDRlab 122-16 board is significantly larger.

The LTC2208 ADC has an SNR of around 78 dB. It corresponds to the effective number of bits of approximately 12.7. I think 14 bits is just enough for this ADC and 2 more bits won't do anything useful.

Anyway, in most projects in this repository, it is enough to change a couple of lines to switch to 16 bits. For example, here are the links to the corresponding lines in the `sdr_transceiver_hpsdr` project:

https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/block_design.tcl#L67
https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/rx.tcl#L145

**Comment by enthru** [comment]
Got it! Thanks for the info and quick answer.
