### ISSUE TITLE
Need help modifying adc_recorder code

### ISSUE THREAD

**Issue by EnPassant123** [pavel-demin/red-pitaya-notes#1090]
Hi,
I am an undergraduate student who is working on a radar project.

My goal is the following:

I would like to get data from both ADCs at 2 megasamples / second. I have a sawtooth generator which creates a sawtooth wave for the VCO of the radar, and the sawtooth generator also has a square wave output which basically indicates whether to collect data or not. The square wave output is high when the sawtooth voltage is increasing, and it goes to zero during the time when the sawtooth voltage resets (this happens in ~10 microseconds). The sawtooth frequency is 250 hertz, so the number of samples collected would be around 16,000 samples (8,000 for each channel). I would like to send all of these samples to a computer through Ethernet, where I will do stuff like taking the FFT. 

This seems like a combination of your adc_recorder project and your adc_test project. The adc_recorder project outputs 2 MS/s from both ADC channels, and the adc_test project sends the information over Ethernet.  The problem is that the adc_test project doesn't seem to "stream" the data. 

How would I modify the programs to do this:
1. Data collection is started on the rising edge of a GPIO input
2. Data is stored in the first memory location
3. On the falling edge of the GPIO input, data collection stops and some interrupt is generated. 
4. On the interrupt, a program on the CPU sends data from the first memory location to the computer through Ethernet. Meanwhile, data is being written to a second memory location after the rising edge of the GPIO input
5. The cycle repeats (but the CPU program reads from the second memory location while the first location gets overwritten)

I'm also not sure if there's an easier way to accomplish this. (I'm pretty bad at FPGA programming and I've only done it a few times).

**Comment by pavel-demin** [comment]
I would suggest using the IP cores from the `develop` branch and starting with something simpler:
```
ADC->CIC filter->validator->FIFO->AXI hub
```
with the validator trigger input connected to the square wave.

Or maybe even simpler would be to have three continuous data streams (with triggering done in software in code running on the computer):
- ADC samples from IN1
- ADC samples from IN2
- samples from a pin connected to square wave

I am afraid I cannot help more than this.
