### ISSUE TITLE
Fortran Runtime Error in ft8d.f90

### ISSUE THREAD

**Issue by sciurus** [pavel-demin/red-pitaya-notes#1092]
### Description of the setup:

 * Device: TRX-DUO
 * SD card image: red-pitaya-alpine-3.14-armv7-20220322.zip
 * Application: sdr_transceiver_ft8
 * Other relevant information:

### Description of the problem:

I've been running an FT8 skimmer for several months. Recently, it started failing to function with the error below. I thought I might have corrupted the filesystem, so I reformatted the SD card, downloaded the latest image, and set up the system again from scratch. However, it is still failing with the same error.

Excerpt from decode-ft8.log:
```
Sun Apr 23 21:43:01 UTC 2023
Sleeping ...
Sun Apr 23 21:44:00 UTC 2023
Recording ...
Terminated
Decoding ...
At line 33 of file ft8d.f90 (unit = 10)
Fortran runtime error: Cannot open file 'ft8_*_230423_2143.c2': No such file or directory

Error termination. Backtrace:
```

### Steps to reproduce the problem:

On my system, they are

 1. Configure  sdr_transceiver_ft8 to skim 40M-6M
 2. Start it
 3. Observe that in /dev/shm the decodes_*.txt files are empty and decode-ft8.log shows the error above repeating.

**Comment by pavel-demin** [comment]
The `Terminated` message indicates that the `write-c2-files` program was killed before it could write the output files and exit normally. So it seems that the `write-c2-files` program is hanging for some reason.

If it worked before and does not work now, the it looks like a hardware problem.

Maybe you could check if other applications like LED blinker or SDR transceiver are still working.
