### ISSUE TITLE
Embedded GNURadio

### ISSUE THREAD

**Issue by Dystroxic** [pavel-demin/red-pitaya-notes#1096]
### Description of the setup:

 * Device: SRDLab 122-16
 * SD card image: red-pitaya-alpine-3.14-armv7-20220322.zip
 * Application: Embedded SDR Transceiver
 * Other relevant information:

### Description of the problem:

I've been working with the SDRLab 122-16 with GNURadio on a remote device, connecting to the "SDR Transceiver" application on the SDRLab. Unfortunately, this configuration is not working for our application, as there appears to be a round-trip latency (send samples to SRDLab to transmit over OUT1, receive that signal from IN1 and send back to remote application) of several hundred milliseconds. This is making it impossible to implement a CSMA/CA algorithm.

I'd like to try running our application on the SDRLab itself, instead of using a remote machine to connect to the SDRLab. Is it possible to install GNURadio on the SDRLab itself? I noticed that "SDR Transceiver Embedded" project directory has a [GNURadio directory](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/sdr_transceiver_emb/gnuradio), which suggests that this has been done before, but I'm having difficulty. First, the partition size of the precompiled Alpine image is far too small to install Python and GNURadio, and second, there is no existing GNURadio Alpine apk for ARMv7, as far as I can tell.

**Comment by pavel-demin** [comment]
With the 1.25 MSPS rate, I would expect the buffers to contribute no more than 10 milliseconds to round-trip latency. The code running on the Red Pitaya board has buffers for 2048 samples (less than 2 ms at 1.25 MSPS).
