### ISSUE TITLE
HPSDR Analog Inputs

### ISSUE THREAD

**Issue by GitJiggyWiddit** [pavel-demin/red-pitaya-notes#1103]
Hello,

I'd like to make use of the analog inputs for the HPSDR transceiver application but the documentation on it seems thin. I can't find anything that indicates what voltage on the inputs corresponds to what values of forward/reverse power, voltage, or current. I understand the maximum voltage for these inputs is 3.5V so I want to be careful not to damage them.

In short:
- Is there a SWR bridge on the market I can use that outputs the range desired by the analog inputs?
- Is there a voltage/current sensor on the market that can do the same?
- If not, how can I adapt a SWR bridge/voltage/current sensor to work in the required voltage range? 
- Are there tables or equations that define what input voltage corresponds to what value of power/voltage/current?

Thanks!
Ed

**Comment by pavel-demin** [comment]
I am afraid that I do not have answers to these questions.

If I am not mistaken, the XADC inputs are unbuffered and it would be better to have op-amp based buffers between the measured voltages and the inputs.

I think that it would be possible to use these op-amps to divide or amplify the measured voltages to bring them to the range of the inputs.
