### ISSUE TITLE
Checking the ADC.

### ISSUE THREAD

**Issue by DMIAMENTGO** [pavel-demin/red-pitaya-notes#1107]
Hello, Pavel!

After a thunderstorm, RX1 stopped working in my TRX-DUO receiver. After checking, I assumed that the input circuit of the ADC had burned out. I decided to swap RX1 and RX2. But after that, switching to the transceiver mode (sdr_transceiver, HPSDR, the done LED lights up) is accompanied by a server shutdown (SDR stops responding to requests through the browser, ping 192.168.1.100). Do you have any self-diagnostic software to understand what exactly is not working? Does the transceiver start without an ADC at all?

R3DCY, Dmitriy

**Comment by DMIAMENTGO** [comment]
Thanks for your response.
The LED blinker does not blink.
Are the clocking lines (CLKOUT on chip) between two chips on the board or connected separately to the main chip? Is it possible to run with only one ADC chip?

**Comment by pavel-demin** [comment]
These questions should be asked to TRX-DUO developers.

I have never seen the TRX-DUO schematics and I have never tested my applications with TRX-DUO.

I assume that only one ADC clock is used because it works with my applications that do not use the second ADC clock.

**Comment by DMIAMENTGO** [comment]
Well, thank you.
I will read the datasheet on the ADC chip and check them individually.
