### ISSUE TITLE
Issue with Python Interface "mcpha.py".

### ISSUE THREAD

**Issue by ubal2** [pavel-demin/red-pitaya-notes#1124]
### Description of the setup:

 * Device: STEM_125-10_v1.0
 * SD card image: STEMlab_125-xx_OS_1.04-28_beta.img
 * Application: MCPHA

### Description of the problem:

Hello Pavel,

We are using the Red Pitaya for spectral acquisitions with the MCPHA application. We can successfully perform acquisitions using the "redpitaya-multichannelanalyser" app by sefffal, as well as the MCPHA app using the "mcpha.tcl" control software. However, we are experiencing issues with the Python interface "mcpha.py". While it connects to the Red Pitaya, it fails to display any acquisitions.

Could you please provide us with any suggestions or assistance?

Thank you.

**Comment by pavel-demin** [comment]
Please make sure that the version of the application running on the Red Pitaya board and the version of the control program are the same.

The easiest way would be to follow the getting started instructions at the following link and download release [20231004](https://github.com/pavel-demin/red-pitaya-notes/releases/tag/20231004) of the SD card image and control program:
http://pavel-demin.github.io/red-pitaya-notes/mcpha/#getting-started-with-ms-windows
