### ISSUE TITLE
Hotspot mode not working

### ISSUE THREAD

**Issue by davidhay45** [pavel-demin/red-pitaya-notes#1129]
### Description of the setup:

 RP 125-14
[ * SD card image:]red-pitaya-alpine-3.18-armv7-20240204.zip
 * Application:
 * Other relevant information:

### Description of the problem:
I am using a wifi dongle that works in client mode but will not function when configured as a hotspot

### Steps to reproduce the problem:

 1. Fresh download copied to sd card
 2. Wifi dongle plugged in.
 3. Power on - no connection
 4. Connect via ethernet
 5. Reconfigure to client mode - works ok
 6. Tried using earlier version of sd image (red-pitaya-alpine-3.14-armv7-20220322) - same result.

**Comment by pavel-demin** [comment]
Please provide more information (model, USB ID) about the USB/Wi-Fi adapter. You can see the USB ID in the output of the `lsusb` command.

The currently enabled drivers that I regularly test are for the following USB/Wi-Fi chips:
- RTL8188EU
- RT5370
- AR9271

If your USB/Wi-Fi adapter does not have one of these chips, then it would be quite difficult for me to reproduce your problem.

I think that it would be easier to use a 150 Mbps USB/Wi-Fi adapter with the RTL8188EU chip. I think that current models of the following 150 Mbps USB/Wi-Fi adapters use the RTL8188EU chip:
- EDIMAX EW-7811Un
- D-Link DWA-121
- TP-Link TL-WN725N
- TP-Link TL-WN722N

**Comment by davidhay45** [comment]
lsusb simply gives:

Bus 001 Device 001: ID 1d6b:0002 and the item is labelled 802.11n.

I will buy one of the adaptors you mention and hoepfully that will solve my issue.


Thanks for your help.


73's David
