### ISSUE TITLE
Ethernet Connectivity Issues with Red Pitaya Boards

### ISSUE THREAD

**Issue by Yikai-Xia** [pavel-demin/red-pitaya-notes#1135]
### Description of the setup:
**Device**: Red Pitaya 125-14
**SD card image:** downloaded from Alpine with pre-built applications
**Application:** Custom modified adc_test app; originally single-channel ADC downsampling by a factor of 4, now modified for dual-channel downsampling by a factor of 8, with a 500 Mbps Ethernet transfer rate.
**Other relevant information:** Setup includes 4 Red Pitaya boards grouped in a chassis with unified power supply at 5V 2A. No individual cooling fans for each board, but there are 4 fans on the side of the chassis. The boards are synchronized for data collection by a 1kHz trigger signal input to the pins.

### Description of the problem:
The setup generally operates correctly with a total data transfer rate of 2 Gbps across all four boards. A client program written in Python on my computer handles data receive, storage and post-processing, typically running for about 5 minutes. However, two days ago, two of the boards suddenly could no longer connect to the Ethernet without any prior high-load operation. This issue occurred just after a new bitstream file was added and saved and the system was rebooted. But the day before this happened, there had been a data collection done for about 15 minutes (which is the first time I've done this for so long), but no anomalies occurred during this.

Restarts did not resolve the issue. Normally, a proper Ethernet connection shows green light flashing; now, only a yellow light is visible. Re-imaging the SD card and even using the official image did not restore functionality, as only the yellow light showed without the heartbeat indicator light.

Could you please provide any insights into potential causes of this issue and any recommended steps to address the problem if the same functionality is desired. Thank you so much!

**Comment by pavel-demin** [comment]
If everything worked and then stopped working, that sounds like a hardware problem to me.

I think that only Red Pitaya support could help you solve this kind of problem.
