### ISSUE TITLE
Question about exp_n_tri_io and exp_p_trio_io_io

### ISSUE THREAD

**Issue by DavidMariadasa** [pavel-demin/red-pitaya-notes#1143]
Hi Pavel,

first and foremost, thank you for all the work in this project.

I am struggling a bit to understand the definitions of exp_n_tri_io and exp_p_trio_io_io in the Vivado Projects.
I want to use the Exp pins to implement differential trigger signal using an IOBUFDS. Now n is defined as Inout, p is defined as out. I would like to know for which reason they are defined this way, as I could not find the right information on the RedPitaya page. 

Best Regards,
David

**Comment by pavel-demin** [comment]
As far as I know, the `exp_p_tri_io` and `exp_n_tri_io` ports are defined as `inout` in cfg/ports.tcl.

They are defined this way for no particular reason. I probably chose the most obvious configuration for these ports as the default configuration.

In some projects, these ports are redefined to meet the requirements of these projects.

So if you need these ports to be defined as differential inputs, just redefine them.

I think the simplest example of port redefinition is  [led_blinker_slave](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/led_blinker_slave).
