### ISSUE TITLE
errors on building from source using vitis running on ubuntu

### ISSUE THREAD

**Issue by zkf0100007** [pavel-demin/red-pitaya-notes#1146]
I installed ubuntu 18.04 virtual machine on vmware, and installed vitis 2023.1 on ubuntu.
When I building from source following https://pavel-demin.github.io/red-pitaya-notes/sdr-receiver/ 
I could generate bitstream using 
`make NAME=sdr_receiver bit`
but some errors occured:
`source helpers/build-all.sh`
the error shows as following:
`qemu: Unsupported syscall: 397`
I wonder if I should use Debian insted of Ubuntu?
Could you give more detailed description on how to buildinf from souce?
Thanks!

**Comment by pavel-demin** [comment]
I do not see any problem with the commands that you are using. I am using the exact same commands. Only I am using Debian 12 as the operating system on my computer.

Ubuntu should be OK, but 18.04 is a very old version. I would try a newer version. For example 22.04.

**Comment by zkf0100007** [comment]
I changed OS from Ubuntu 18.04 to Debian 12 as suggested.
Bootimage generated successfully!

Thank you very much!
