### ISSUE TITLE
Where is the standalone SDR example building on RedPitaya using external audio CODEC?

### ISSUE THREAD

**Issue by zkf0100007** [pavel-demin/red-pitaya-notes#1147]
It seemed that you have wrote a standalone SDR example building on RedPitaya using external audio CODEC.
The standalone SDR could run separately without usin PC.
I could not find the example now.

**Comment by pavel-demin** [comment]
I had it but deleted the project last year. It was too difficult to maintain and did not attract enough interest to justify the effort. Here is the latest version before deletion:

https://github.com/pavel-demin/red-pitaya-notes/tree/688661d7320aaa85e7180406435dcb5c5358b946/projects/sdr_transceiver_emb

**Comment by zkf0100007** [comment]
OK. I got it.
Thanks!
