### ISSUE TITLE
Disable mmc readonly mode

### ISSUE THREAD

**Issue by mrengineer** [pavel-demin/red-pitaya-notes#1150]
Dear Pavel, thank you for your repo!

Please, help with question how to disable read-only for mmc card? I want to debug my app. Therefore I have to rewrite app frequently

**Comment by pavel-demin** [comment]
If you are using an SD card image based on Alpine Linux, then the following aliases are defined in `/root/.profile`:
```
alias rw='mount -o rw,remount /media/mmcblk0p1'
alias ro='mount -o ro,remount /media/mmcblk0p1'
```
So you can make the SD card writable by running the `rw` command from the command line. The `ro` command can be used to make the SD card read-only.

Another possibility is to use an SD card image based on Debian Linux. When using such an SD card image, the SD card is always writable. You can find a link to such an SD card image in the SD card image section of the LED blinker notes:
http://pavel-demin.github.io/red-pitaya-notes/led-blinker/#sd-card-image

**Comment by mrengineer** [comment]
Thank you!
