### ISSUE TITLE
Redpitaya and DMA(Deep Memory Acquisition)

### ISSUE THREAD

**Issue by OlliMir** [pavel-demin/red-pitaya-notes#1159]
Good day, I hope for your help. Not long ago I became the owner of redpitaya 122.88 16. I use it as a signal generator and receiver using SCPI commands in MATLAB. There was a need to work with the generation and reception of a signal much larger than 16384 characters. I found information about DMA on the official website, followed the steps indicated to increase the buffer. The next step was to try to get data on DMA using commands like ACQ:AXI:START?, but no data is received, an error occurs. Maybe you have encountered this? Or tell me how else to solve the problem with a small buffer size.

**Comment by pavel-demin** [comment]
I cannot help you with SCPI. The SCPI software for the Red Pitaya boards is developed by Red Pitaya. It would be more efficient to contact them directly for any questions regarding their software.
