### ISSUE TITLE
Decoding Problem with FT8 Transceiver

### ISSUE THREAD

**Issue by df6dbf** [pavel-demin/red-pitaya-notes#1162]
Hello Pavel,
i have Problems to get the FT8 Skimmer working. Device is a Red Pitaya Stemlab 125-14 using the latest Image from your Site.
Call and Grid-Locator is added in upload-ft8.sh
The Bands are defined in write-c2-files.cfg.

In /dev/shm/decode-ft8.log I got the following Message.

Error termination. Backtrace:
Wed Dec 25 11:39:01 UTC 2024
Sleeping ...
Wed Dec 25 11:40:00 UTC 2024
Recording ...
Error on line 16 in configuration file.
Decoding ...
At line 33 of file ft8d.f90 (unit = 10)
Fortran runtime error: Cannot open file 'ft8_*_241225_1140.c2': No such file or directory

Resulting in no decodes in the decodes*.txt files and no Upload to PSKreporter.

73s Holger, DF6DBF

**Comment by pavel-demin** [comment]
Hello Holger,

Have you edited the configuration file `write-c2-files.cfg`?

The error message indicates an error in this configuration file. Please check if all bands are separated by commas and that there is no trailing comma after the last band.

Best regards,

Pavel

**Comment by df6dbf** [comment]
That is the point that confuses me:
There are no trailing comma after the last selected Band. :/

![image](https://github.com/user-attachments/assets/6597515c-cf56-45a4-b3d4-278d2724cd6c)

**Comment by pavel-demin** [comment]
Thank you for the screenshot. There should be a comma on the uncommented line with the 21 MHz frequency.

**Comment by df6dbf** [comment]
Oh! It seems i need new glasses soon! 
Thanks for your help and the excellent work!

Holger

**Comment by df6dbf** [comment]
closed
