### ISSUE TITLE
Question: Using IN2 and OUT2 for audio processing

### ISSUE THREAD

**Issue by dc1rdb** [pavel-demin/red-pitaya-notes#135]
Hi Pavel, on your "Embedded SDR Transceiver", would it be possible to configure IN2 and OUT2 as microphone input and headphone/speaker output to get rid of the external sound card?
Really appreciate your work - thanks a lot!
Kind regards,
Robert DC1RDB

**Comment by pavel-demin** [comment]
Hi Robert,

Thanks for your interest in my embedded SDR transceiver project.

I think that it's already possible to test this kind of configuration with the current version.

It should be enough to set the frequency to zero for the source and sink blocks connected to IN2 and OUT2.

Best regards,

Pavel

**Comment by dc1rdb** [comment]
Thanks Pavel, will try this as soon as I get the chance!
