### ISSUE TITLE
VOX PTT mod

### ISSUE THREAD

**Issue by effeerre75** [pavel-demin/red-pitaya-notes#142]
Just made a little mod you can find it here:

https://github.com/effeerre75/Gnuradio-VOX-PTT

In this way if a signal come in the PTT is keyed (VOX), really handy for digital mode.
Only a little change on the sink block: PTT goes to an int value.

**Comment by pavel-demin** [comment]
The PTT type is set to int with [this pull request](https://github.com/pavel-demin/red-pitaya-notes/pull/914).
