### ISSUE TITLE
Accessing Digital IO using dac_player PL

### ISSUE THREAD

**Issue by JBosc** [pavel-demin/red-pitaya-notes#167]
Hi,

I'm trying to modify your dac_player's block design so I can use Digital IO. The memory mapping of your block design seems different from the original red pitaya and I can't find the good memory address to set direction then read or write IO. It seems also that register for DIO aren't mapped in block design, but I might be wrong, I don't have a lot of experience in fpga design.

What should I do to access DIO?

Thank you!

**Comment by pavel-demin** [comment]
Could you please explain how you are planning to use the digital IO?

**Comment by JBosc** [comment]
I want to generate a pulse of approx. 100ms each second. It will act as a chip select. Right now I already send signal with DAC each second and I want to trigger CS just before.

**Comment by pavel-demin** [comment]
Please have a look at the [Scanning system](http://pavel-demin.github.io/red-pitaya-notes/scanner) project. It does almost exactly that you describe. It continuously outputs signals to DAC and generates trigger pulses on the GPIO pins. The code that calculates the DAC samples starts from line 182 in [projects/scanner/server/scanner.c](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/scanner/server/scanner.c#L182).

**Comment by JBosc** [comment]
Oh I'll check. Thanks for your help!
