### ISSUE TITLE
dds_compiler and redpitaya DAC

### ISSUE THREAD

**Issue by cedricboudinet** [pavel-demin/red-pitaya-notes#174]
Hello

I am trying to send the output of a dds bloc (generating a 1MHz sine wave) to the DAC (using axis_red_pitaya_dacIP bloc) in Vivado.

I tried a direct connection and I had no output.
Then I tried to insert a width converter and a clock converter between the two blocs, then the dac has an output but it seems erratic (frequency much higher than 1MHz, very noisy, ...).

We set these parameters in the dds compiler :
 - Fixed phase increment
 - 1MHz Output Frequancy (Phase Increment is 0h83126E)

Regards
Cedric

**Comment by pavel-demin** [comment]
Hello Cedric,

I have a test project with dds_compiler connected directly to axis_red_pitaya_dac:
https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/dac_test

Last time when I tested it, it worked quite well.

In this project, both DDS and DAC are clocked from a PLL connected to the ADC clock.

Here is how it looks like with all the unneeded blocks removed:
![dds_dac](https://cloud.githubusercontent.com/assets/8037893/12886079/48bd2d42-ce6b-11e5-83da-65bc9ebde58c.png)

Best regards,

Pavel

**Comment by cedricboudinet** [comment]
I managed to make it working. Thanks.
