### ISSUE TITLE
how can user add missing ftdi_sio.ko kernel module

### ISSUE THREAD

**Issue by dragniko** [pavel-demin/red-pitaya-notes#205]
Is it possible to modify your red-pitaya-notes scripts that build RP image (uname -r returns Linux 4.0.0 Xilinx) by users in order to include "ftdi_sio.ko" module. Or where one can find necessary kernel headers and source files to compile ftdi module directly on RP board?
Thanks for your time and effort,
Dragan

**Comment by pavel-demin** [comment]
You can reconfigure and rebuild Linux kernel with the following commands:
```
cd tmp/linux-xlnx-xilinx-v2015.4
make mrproper
make ARCH=arm xilinx_zynq_defconfig

make ARCH=arm menuconfig

make ARCH=arm CFLAGS="-O2 -mtune=cortex-a9 -mfpu=neon -mfloat-abi=softfp" CROSS_COMPILE=arm-xilinx-linux-gnueabi- UIMAGE_LOADADDR=0x8000 uImage
cp arch/arm/boot/uImage ../../
```

I've added ```CONFIG_USB_SERIAL=y``` and ```CONFIG_USB_SERIAL_FTDI_SIO=y``` to linux-xlnx-xilinx-v2015.4.patch. It's currently in the develop branch:
https://github.com/pavel-demin/red-pitaya-notes/blob/develop/patches/linux-xlnx-xilinx-v2015.4.patch
