### ISSUE TITLE
ADC redpitaya

### ISSUE THREAD

**Issue by issmaf44** [pavel-demin/red-pitaya-notes#207]
Dear Pavel,
  Is it possible to sample the ADC's redpitaya at 50 MHz?
Best regards

**Comment by pavel-demin** [comment]
It's better to ask this kind of questions on the Red Pitaya forum:

http://forum.redpitaya.com/

As far as I know, it's not impossible but involves some soldering.

You can find more information on the following wiki pages:

http://wiki.redpitaya.com/index.php?title=Red_Pitaya_Board_HW_Schematics
http://wiki.redpitaya.com/index.php?title=External_ADC_clock
