### ISSUE TITLE
AXI Stream to Memory mapped

### ISSUE THREAD

**Issue by jeanminet** [pavel-demin/red-pitaya-notes#212]
Hello Pavel,

Thanks a lot for your very helpful work !
In your `sdr_transceiver` project, you use a Xilinx `FIFO generator` core in combination with two custom cores (`axi_axis_reader` and `axi_axis_fifo`) in order to have a memory mapped access to the data stream: 

![screenshot from 2016-04-13 18 02 08](https://cloud.githubusercontent.com/assets/1735094/14500230/9540a522-01a1-11e6-9d26-10dfcc291c4b.png)

It looks like this functionality could be implemented with the Xilinx [`AXI-Stream FIFO`](http://www.xilinx.com/support/documentation/ip_documentation/axi_fifo_mm_s/v4_1/pg080-axi-fifo-mm-s.pdf) core:

![screenshot from 2016-04-13 18 30 00](https://cloud.githubusercontent.com/assets/1735094/14501156/4f39fafc-01a5-11e6-8e15-b4d39312ccdb.png)

I was wondering if I missed something. Does your combination provide better throughput ?

Best,
Jean

**Comment by pavel-demin** [comment]
Hello Jean,

> Does your combination provide better throughput ?

Throughput - I don't know, maybe. Features - yes.

I've once simplified the AXI4-Lite interface in all my AXI4-Lite cores with the following commit: https://github.com/pavel-demin/red-pitaya-notes/commit/663e313b6ccf3cb0a866e85cce2f7de34704d633.

I've tried several AXI and AXIS FIFO cores provided by Xilinx but without much success. They behaved strangely, had some features that I didn't need, missed some features that I needed.

My projects often require the following features:
 - mixed ports widths,
 - s_axis_tready and m_axis_tvalid always high,
 - m_axis_tdata low if FIFO is empty.

Both [axi_axis_reader](https://github.com/pavel-demin/red-pitaya-notes/tree/master/cores/axi_axis_reader_v1_0) and [axis_fifo](https://github.com/pavel-demin/red-pitaya-notes/tree/master/cores/axis_fifo_v1_0) are very simple and do exactly that I need.

Best regards,

Pavel

**Comment by jeanminet** [comment]
That makes sense.
I didn't realize the `axis_fifo` core was so simple !
