### ISSUE TITLE
VNA: Channel selection would be desirable

### ISSUE THREAD

**Issue by ted051** [pavel-demin/red-pitaya-notes#242]
Hello Pavel, 
grateful for your development I suggest a little improvement: manual selection of the input- and output channel. This would mean, that Red Pitaya could work as transceiver and as VNA in the same case.
Best regards, Wolfgang (DH1AKF)

**Comment by pavel-demin** [comment]
Hello Wolfgang,

I'm not sure if I understand how it would improve the VNA.

Current version already uses two inputs in case someone wants to implement a VNA with two inputs as described at the following link:
http://forum.redpitaya.com/viewtopic.php?t=266&p=5266#p5266

Implementing a selector for the outputs is too much work and I don't understand how it could be useful.

Best regards,

Pavel
