### ISSUE TITLE
Alex connections effect the pre-amplifier.

### ISSUE THREAD

**Issue by pe0mgb** [pavel-demin/red-pitaya-notes#255]
Hallo Pavel,
I have build a transceiver using the Red Pitaya and your software. It works perfect. I'm very happy with it.
My first set up was using the DIO0_P pin for PTT and DIO1_P pin for switching an LNA.
Filter control was manually with a rotary switch.
When the ALEX SPI bus control came available, I build it and it is controlling my filters perfect.
I also build the Alex attenuators (10 and 20dB). Now here I have a problem. When you add Alex to the hardware options in de hardware config of HPSDR the roll down menu of the ATT(enuator) is extended.
You have now first the original 0 dB and -20 dB ( I was using to control the LNA) and new -10 dB, 20 dB, 30 dB, 40 dB and 50dB. The -10 dB, 20dB and 30 dB is controlling the attenuator perfectly but  the LNA is switching on when I operate one of the 3 levels. Clicking on the 0 dB switch off the attenuators but LNA is still active. After clicking the first -20 dB also the LNA is switched off. I can not operate the attenuators without switching on the LNA.
I also see when no LNA or attenuator is in the line and I switched on the LNA (0 dB) , the receiver noise level goes 20 dB down.
What is my misunderstanding here and what I'm doing wrong? Is the DIO1_P pin not meant the way I'm using it to control a LNA?

Thanks in advance,

Gert PE0MGB

**Comment by pavel-demin** [comment]
Hello Gert,

Controlling a LNA with the DIO1_P pin is perfectly OK.

I've just checked all the ATT settings and corresponding LNA and ALEX outputs and here is what I've obtained:

ATT | +20 dB (LNA) | -20 dB (ALEX) | -10 dB (ALEX)
--- | --------------- | ------------- | ------------
  0 | On              | Off           | Off
-20 | Off             | Off           | Off
-10 | On              | Off           | On
-20 | On              | On            | Off
-30 | On              | On            | On
-40 | Off             | On            | Off
-50 | Off             | On            | On

Looks quite logical to me. The -40 and -50 settings control the attenuators without switching on the LNA.

> I also see when no LNA or attenuator is in the line and I switched on the LNA (0 dB) , the receiver noise level goes 20 dB down.

I think that it's OK. PowerSDR shifts the spectrum levels when it switches on the LNA.

Best regards,

Pavel
