### ISSUE TITLE
Images of HPSDR multireceiver / wspr / VNA

### ISSUE THREAD

**Issue by on3vna** [pavel-demin/red-pitaya-notes#270]
Pavel,

What is the correct procedure to get those images on the red-pitaya disk ?

73 de ON3VNA
Johan

**Comment by pavel-demin** [comment]
For HPSDR multireceiver and VNA, just copy the content of the zip file to an empty SD card.

VNA is also available via [Red Pitaya application marketplace](http://bazaar.redpitaya.com/).

For multiband WSPR transceiver, unpack the zip file and then write the SD card image to a SD card using `dd` or [Win32 Disk Imager](http://sourceforge.net/projects/win32diskimager/).
