### ISSUE TITLE
DiscoRedTRX: No PTT signal

### ISSUE THREAD

**Issue by ted051** [pavel-demin/red-pitaya-notes#311]
After switching to the WDSP library I could send any PTT signal from STM32F7 to Red Pitaya, but there was no effect. (Have adapted the STM program to your new command number "8" , but no success.)
Best regards, Wolfgang

**Comment by pavel-demin** [comment]
Solved with the addition of the PTT functionality to the STM32F7 UI code:
https://github.com/pavel-demin/DiscoRedTRX/blob/master/ui/Src/main.c#L314
