### ISSUE TITLE
VNA Linux Required Libraries

### ISSUE THREAD

**Issue by ptamike** [pavel-demin/red-pitaya-notes#313]
Hi Pavel

I've installed the VNA control software on several Linux boxes and none have had the essential libfreetype6-dev library installed. It might be helpful for others if you add this package to the list of requirements.

Mike - G4WNC

**Comment by pavel-demin** [comment]
Hi Mike,

Thanks for testing the VNA client. I've added libfreetype6-dev to the list of the required libraries.

Best regards,

Pavel
