### ISSUE TITLE
Blinking led introduces noise and clicks on other receivers

### ISSUE THREAD

**Issue by waterwin** [pavel-demin/red-pitaya-notes#323]
Although a program with the I am alive signal of a blinking led is nice, this introduces noise. Can it be switched of or at least not be blinking every second but maybe once every 10 minutes.
Even nicer would be a user settable parameter to have or have not a blinking led or the time it is blinking.
Just on would be good enough as long as the on is not a pwm function.

**Comment by pavel-demin** [comment]
Thanks for spotting this problem. I'll remove the blinking led code from my radio related projects.

**Comment by pavel-demin** [comment]
I've removed the blinking led code from almost all my projects.
