### ISSUE TITLE
SDR_Tranceiver Example

### ISSUE THREAD

**Issue by tilman1** [pavel-demin/red-pitaya-notes#324]
Dear Pavel

1) Just a small hint/suggestion: A hint that sdr-transceiver needs to be started on the red pitaya would help the newcomer. I wondering about the argument that either can be 1 or 2. I would guess that it is the input channel.

2) Would there be a program available (on linux) that connects to the server and shows me an fft water fall? There is the sdr_transceiver_fft project  -- I understand that it is abandoned however...

Many thanks
Tilman

**Comment by pavel-demin** [comment]
Dear Tilman,

I think that the answers to both questions can be found in the following blog post:
http://redpitaya.com/gqrx-with-the-red-pitaya

sdr-transceiver can be used with SDR# and HDSDR under Windows and with QUISK, Gqrx under Linux.

I'll add the commands to start the server to my notes.

The sdr_transceiver_fft project project is not related to the ability to show an fft water fall on Linux machine. It's related to the embedded SDR project:
http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-emb

Best regards,

Pavel
