### ISSUE TITLE
development-machine step missing: create Host-only network

### ISSUE THREAD

**Issue by MustBeArt** [pavel-demin/red-pitaya-notes#382]
In the Virtualbox instructions in development-machine, it says to enable Adapter 2 attached to "Host-only Adapter". This cannot be done unless there is an existing Host-only network.

Solution: After starting VirtualBox, choose File->Preferences, Network, Host-only Networks, and click the green icon to add one. Click OK.

**Comment by pavel-demin** [comment]
Thanks for spotting this problem. I've just added the missing part to the instructions.
