### ISSUE TITLE
Audio Codec WM8731 and CW latency

### ISSUE THREAD

**Issue by df5sf** [pavel-demin/red-pitaya-notes#420]
Hello,
After X-mas I will take some time to build my SDR-Transceiver.
my first question:
has anybody meassured the latency in CW receive with WM8731 and what is your experience in CW ?
and the second question:
if I use WM8731 where are the CW/SSB-filters. In FPGA or in PC (HPSDR software) ?
and the last question:
Has anyone experience and built an SDR-Transceiver with piHPSDR on raspberry pi?

Many thanks an hny.

73
Uli DF5SF
uli)at(df5sf-qrp.de

**Comment by pavel-demin** [comment]
Hello Uli,

As far as I know, the latency is quite acceptable for the CW operation. For example, Yevgeni RZ3QS regularly uses Red Pitaya for the CW operation. Here is a link to one of his videos:
https://www.youtube.com/watch?v=lJD54oXqTp8

The CW/SSB filters are in PowerSDR mRX PS.

The latency depends on several settings in PowerSDR mRX PS such as buffer size, filter type, sample rate.

I'd say that the following PowerSDR mRX PS settings would be a good starting point:
 - sample rate 192 kSPS
 - buffer size 512
 - CW RX buffer size 64
 - Low Latency filter

The CW receive latency with these settings is around 55 ms.

Best regards,

Pavel
