### ISSUE TITLE
Create safe temporary directories 

### ISSUE THREAD

**Issue by hmaarrfk** [pavel-demin/red-pitaya-notes#446]
Hi, 

Great work. This is awesome. Very well documented.

I just wanted to add a small suggestion: 

In `scripts/debian.sh`, `boot_dir` and `root_dir` should be set with `mktemp` instead of statically. That way we don't accidentatlly clobber something. You can use

```sh
boot_dir=`mktemp -d RPboot.XXXXXXXXXX`
root_dir=`mktemp -d RProot.XXXXXXXXXX`
```

**Comment by pavel-demin** [comment]
Thanks for the suggestion. I've just added `mktemp` to all my debian and ubuntu scripts with [this commit](https://github.com/pavel-demin/red-pitaya-notes/commit/c8f7819fd447b137f20bbf690af2a974f8faf2ca).
