### ISSUE TITLE
Debootstrap cannot download Debian

### ISSUE THREAD

**Issue by XYEFA** [pavel-demin/red-pitaya-notes#455]
I seem to be having an issue getting Debian - Failed getting release file http://httpredir.debian.org/debian/dists/jessie/Release

How can I resolve this? My network is fine. The messages I get are:

W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving Release 
E: Failed getting release file http://httpredir.debian.org/debian/dists/jessie/Release

**Comment by pavel-demin** [comment]
Are you running one of the `debian*.sh` scripts? On what kind of machine?

**Comment by XYEFA** [comment]
Yes - 

`sudo sh scripts/image.sh scripts/debian-ecosystem.sh red-pitaya-ecosystem-0.95-debian-8.6-armhf.img 3725`

**Comment by XYEFA** [comment]
Seems to take forever on my end ... :/ From my Linux box and my Mac Laptop ...

**Comment by pavel-demin** [comment]
Looks like it redirects you to a server that is currently down. As a solution, I'd just replace  httpredir.debian.org/debian with an address of a mirror that works for you. Here is a list of mirrors:
https://www.debian.org/mirror/list

**Comment by XYEFA** [comment]
Thank you Pavel! I think you can close this.

Regards!

**Comment by JuiP** [comment]
can you please tell me how do you replace httpredir.debian.org/debian ? Just a beginner

**Comment by pavel-demin** [comment]
> can you please tell me how do you replace httpredir.debian.org/debian ?

I'm afraid that this question is too general for me to answer specifically. Please try to explain what is exactly your problem.

My general answer is to edit the script file you're trying to run and set the `mirror` variable to the URL that works for you.

**Comment by JuiP** [comment]
Got it figured out! Thanks :)
