### ISSUE TITLE
how did you create the vna.exe

### ISSUE THREAD

**Issue by dasGringuen** [pavel-demin/red-pitaya-notes#456]
Hi Pavel,

nice repo, it helps a lot!!
I just wanted to ask how did you created the vna.exe in your Vector analyzer tool from the python scripts.

Thanks!

**Comment by pavel-demin** [comment]
I create it using the following two files and py2exe:
https://github.com/pavel-demin/red-pitaya-notes/blob/master/helpers/exec.py
https://github.com/pavel-demin/red-pitaya-notes/blob/master/helpers/setup.py

The command is `python setup.py py2exe`.
