### ISSUE TITLE
Creating virtual machine with Debian 8.6 failure

### ISSUE THREAD

**Issue by dnguyen76** [pavel-demin/red-pitaya-notes#458]
Hi Pavel  

I had tried to create virtual machine with Debian 8.6 but after successful installation , the following message appears during boot : 
```
Feb 23 17:37:53 debian virtualbox-guest-utils[361]: Starting VirtualBox AdditionsNo suitable module for running kernel found ... failed!
Feb 23 17:37:53 debian autofs[363]: Starting automount....
Feb 23 17:37:53 debian virtualbox-guest-utils[361]: failed!
Feb 23 17:37:53 debian systemd[1]: virtualbox-guest-utils.service: control process exited, code=exited status=1
Feb 23 17:37:53 debian systemd[1]: Failed to start LSB: VirtualBox Linux Additions.
Feb 23 17:37:53 debian systemd[1]: Unit virtualbox-guest-utils.service entered failed state.
```
After first boot the 2 following commands must be entered to solve this issue:
**apt-get install build-essential module-assistant
apt-get install linux-headers-$(uname -r)**

Daniel

**Comment by pavel-demin** [comment]
Hi Daniel,

Thanks for spotting this problem. I've added the two missing packages with [this commit](https://github.com/pavel-demin/red-pitaya-notes/commit/2b5e09a9966083e32eef9f0d03bab4cf57ff6b7d). Now, `virtualbox-guest-utils` starts automatically after the installation.

Best regards,

Pavel
