### ISSUE TITLE
qemu-system-arm kernel parameters?

### ISSUE THREAD

**Issue by berni421** [pavel-demin/red-pitaya-notes#477]
Which kernel related parameters should be passed to qemu to boot the pre build images please?

The image partition 1 contains:-
boot.bin
devicetree.dtb
uEnv.txt
uImage

$ file boot.bin devicetree.dtb uImage uEnv.txt 
boot.bin:       data
devicetree.dtb: Device Tree Blob version 17, size=10206, boot CPU=0, string block size=962, DT structure block size=9188
uImage:         u-boot legacy uImage, Linux-4.6.0-xilinx, Linux/ARM, OS Kernel Image (Not compressed), 5180496 bytes, Mon Dec 19 15:17:00 2016, Load Address: 0x00008000, Entry Point: 0x00008000, Header CRC: 0x259B5828, Data CRC: 0xA59FBAE2
uEnv.txt:       ASCII text

First guess. Leaving out boot.bin, and uEnv.txt which appear to have no obvious parameter equivalence in qemu:

$ sudo qemu-system-arm \
  -M virt \
  -cpu cortex-a15 \
  -m 256 \
  -kernel uImage \
  -dtb devicetree.dtb \
  -append "root=/dev/vda2 rw console=ttyAMA0 --" \
  -drive file=/home/vm/realp/red-pitaya-ecosystem-0.95-debian-8.6-armhf 20161219.img,if=none,format=raw,id=hd0 \
  -device virtio-blk-device,drive=hd0 \
  -nographic

sadly gives:-

qemu: fatal: Trying to execute code outside RAM or ROM at 0x00008000

R00=00000000 R01=ffffffff R02=48000000 R03=00000000
R04=00000000 R05=00000000 R06=00000000 R07=00000000
R08=00000000 R09=00000000 R10=00000000 R11=00000000
R12=00000000 R13=00000000 R14=00000000 R15=00008000
PSR=400001d3 -Z-- A svc32
s00=00000000 s01=00000000 d00=0000000000000000
s02=00000000 s03=00000000 d01=0000000000000000
s04=00000000 s05=00000000 d02=0000000000000000
s06=00000000 s07=00000000 d03=0000000000000000
s08=00000000 s09=00000000 d04=0000000000000000
s10=00000000 s11=00000000 d05=0000000000000000
s12=00000000 s13=00000000 d06=0000000000000000
s14=00000000 s15=00000000 d07=0000000000000000
s16=00000000 s17=00000000 d08=0000000000000000
s18=00000000 s19=00000000 d09=0000000000000000
s20=00000000 s21=00000000 d10=0000000000000000
s22=00000000 s23=00000000 d11=0000000000000000
s24=00000000 s25=00000000 d12=0000000000000000
s26=00000000 s27=00000000 d13=0000000000000000
s28=00000000 s29=00000000 d14=0000000000000000
s30=00000000 s31=00000000 d15=0000000000000000
s32=00000000 s33=00000000 d16=0000000000000000
s34=00000000 s35=00000000 d17=0000000000000000
s36=00000000 s37=00000000 d18=0000000000000000
s38=00000000 s39=00000000 d19=0000000000000000
s40=00000000 s41=00000000 d20=0000000000000000
s42=00000000 s43=00000000 d21=0000000000000000
s44=00000000 s45=00000000 d22=0000000000000000
s46=00000000 s47=00000000 d23=0000000000000000
s48=00000000 s49=00000000 d24=0000000000000000
s50=00000000 s51=00000000 d25=0000000000000000
s52=00000000 s53=00000000 d26=0000000000000000
s54=00000000 s55=00000000 d27=0000000000000000
s56=00000000 s57=00000000 d28=0000000000000000
s58=00000000 s59=00000000 d29=0000000000000000
s60=00000000 s61=00000000 d30=0000000000000000
s62=00000000 s63=00000000 d31=0000000000000000
FPSCR: 00000000

**Comment by pavel-demin** [comment]
> Which kernel related parameters should be passed to qemu to boot the pre build images please?

I'm using the pre-built images with the Red Pitaya board.  I never used qemu-system-arm. So, I'm afraid that I can't help you with this.
