### ISSUE TITLE
Use Chan 2 as a frequency reference input

### ISSUE THREAD

**Issue by m1geo** [pavel-demin/red-pitaya-notes#481]
Would it be possible to use the second input channel as a frequency reference for 10 MHz in, either to frequency lock the receiver and transmitter, or, to use as a reference to calibrate the `ppm offset` of the main oscillator?

I notice quite a bit of drift on my board (for instance now, I notice I do not receive any WSPR decodes, and upon checking the receiver is 700 Hz out!)

Thanks, 
George M1GEO

**Comment by pavel-demin** [comment]
Here is a link to a blog post showing how to calibrate the ppm offset:
https://wsprlive.net/?p=111

**Comment by m1geo** [comment]
Thanks; that's exactly what I was looking for
