### ISSUE TITLE
password for Debian with Red Pitaya ecosystem

### ISSUE THREAD

**Issue by joel-pr001** [pavel-demin/red-pitaya-notes#504]
Assuming a login of root, what is the password. I tried "root", "redpitaya", etc.
Thanks, Joel

**Comment by pavel-demin** [comment]
The password can be found in the 'Getting started' section:
http://pavel-demin.github.io/red-pitaya-notes/debian-ecosystem/#getting-started

The default password for the `root` account is `changeme`.
