### ISSUE TITLE
documentation/startup script under Alpine

### ISSUE THREAD

**Issue by F6ITU** [pavel-demin/red-pitaya-notes#595]
Hi
On three different config and 2 different places (2 different red pitaya), 
as instructed at 
http://pavel-demin.github.io/red-pitaya-notes/alpine/
 a copy of the "*start.sh" file of any kind of image on the " topmost directory on the SD card" (when creating the image) doesn't start anything

could it be possible to change the "Getting start" instructions

"Optionally, to start one of the applications automatically at boot time, copy its start.sh file from apps/<application> to the topmost directory on the SD card."

into 

Optionally, to start one of the applications automatically at boot time, copy its start.sh file from apps/<application> to the /etc/local.d/ directory on the SD card.

(just a suggestion, it's probably a pebcak problem from my side, but the suggested path cannot work under Alpine Linux )

MArc

**Comment by pavel-demin** [comment]
Hi Marc,

Actually, copying the start.sh file to the topmost directory on the SD card works. Here is a video showing what an where should be copied:

https://www.youtube.com/watch?v=8piEybrHvWU&t=140

The problem with `/etc/local.d/` that it doesn't exist on the SD card.

Best regards,

Pavel

**Comment by pavel-demin** [comment]
BTW. There is already a script in `/etc/local.d/` that executes `start.sh` from the topmost directory on the SD card. Here is a link to the script:
https://github.com/pavel-demin/red-pitaya-notes/blob/master/alpine/etc/local.d/apps.start

So, nothing should be added to `/etc/local.d/`.

**Comment by davidhay45** [comment]
I had a similar problem and found that the /etc/local.d/apps.start file needed to have execute permissions.  However, this problem only occurred on the 20220322 alpine sd card image file.
