### ISSUE TITLE
App on SD-card with Alpine

### ISSUE THREAD

**Issue by karlskontorp** [pavel-demin/red-pitaya-notes#598]
Thank you Pavel for the nice new SD-card image with all the apps on the card! I have one question, I have used Raspberry Pi in some application, and I have hade "brakdown" of the card when just removing power and not doing a real shutdown. Is it possible to get this with the Red Pitaya too? I suppose it has to do with Linux crashing open files when just removing power. If this could be an issue with RP, a shutdown selection in the menu would have been nice!
Thanks in advance for any answer!

Karl Jan - LA3FY

**Comment by pavel-demin** [comment]
With the new SD card image based on Alpine Linux, the SD card is mounted read-only and nothing is written to the SD card during its normal operation. So, the power can be switched off at any moment without damaging the file system on the SD card.
