### ISSUE TITLE
Question: HPSDR compatible transceiver: number of receivers and related full duplex capabilities

### ISSUE THREAD

**Issue by satfan52** [pavel-demin/red-pitaya-notes#625]
Context of my questions:
I am planning to use the red-pitaya with two cheap transverters that I bough on ebay: a 2M/10m txv and a 70cm/10m txv. I would like to use these 2 transverters to try to operate full duplex in the 24mhz-34mhz frequency range of the red-pitaya in order to access ham satellites  using one of the three following acess modes (a) 2m/70cm , (b) 70cm/2m , (c) 10M/2m mode. I realise it can be done in simplex too, but I would like to conduct some tests in full duplex mode for obvious reasons.

My questions;
The description of the HPSDR compatible projet announces on one hand that the transceiver is composed of 1 transceiver and 2 receivers, however later the text also refers to RX1 being mapped to the IN1 port of the Red Pitaya and RX2 & RX3 being mapped to the IN2 port the Red Pitaya which seems contradictory at first

(1) how many receivers can actually receive signals via the the two ports of the red-pitaya, 2 or 3 ?

(2) Does the application offer the possibility to transmit in full duplex mode using the OUT1 port of the red-pitaya on the transmiting side while receiving concurrently via  RX1@IN1 AND RX2@IN2 AND RX3@IN2 ? 

(3) I understand there is only one transmitter but I am wondering if the hpsdr transceiver server would let the client software use OUT2 instead of OUT1 as this might simplify my rf routing-switching circuit and save me the installation of an external switch 

Thanks
Regards
Peter

**Comment by pavel-demin** [comment]
> (1) how many receivers can actually receive signals via the the two ports of the red-pitaya, 2 or 3 ?

There are two fully functional receivers. There are also two additional receivers that are used by the adaptive pre-distortion (Pure Signal). These two additional receivers are always tuned to the TX frequency.

> (2) Does the application offer the possibility to transmit in full duplex mode using the OUT1 port of the red-pitaya on the transmiting side while receiving concurrently via RX1@IN1 AND RX2@IN2 AND RX3@IN2 ?

Yes, full duplex is possible.

> (3) I understand there is only one transmitter but I am wondering if the hpsdr transceiver server would let the client software use OUT2 instead of OUT1 as this might simplify my rf routing-switching circuit and save me the installation of an external switch

OUT2 is used for the envelope signal.

It's possible to checkout a version of the FPGA configuration just before the envelope signal was added:

https://github.com/pavel-demin/red-pitaya-notes/tree/55330b513dfc2b755a991b6f1bc9bc4a40da147d

This version has four fully functional receivers and one transmitter. With a few relatively simple modifications of the code, the receivers and transmitter can be connected to a combination of inputs and output required for your project.
