### ISSUE TITLE
Explanation of C code for testing frequency counter

### ISSUE THREAD

**Issue by parveennisha** [pavel-demin/red-pitaya-notes#627]
### Description of the setup:

 * Device: RedPitaya board
 * SD card image: 
 * Application: Frequency counter
 * Other relevant information:

### Description of the problem:

I am trying to implement ( http://antonpotocnik.com/?p=519284 ) this project with some modifications. I took an external clock for counting the frequency through the GPIO pin. I don't know the C coding. Is the C code is generated by launching the SDK in vivado? Can you suggest me what are the changes i need to do in C code for getting the output.
Thanks

**Comment by pavel-demin** [comment]
> Is the C code is generated by launching the SDK in vivado?

If you're asking about [counter.c](https://github.com/apotocnik/redpitaya_guide/blob/master/projects/4_frequency_counter/server/counter.c), then this code isn't generated automatically.

> Can you suggest me what are the changes i need to do in C code for getting the output.

I'm not sure if I understand why the C code should be changed.

If you've only modified the path of the input signal in the FPGA configuration, then I think that the C code should work as it is

Anyway, I'd suggest to contact the author of the code with this question.
