### ISSUE TITLE
Multi-band FT8 receiver/decoder?

### ISSUE THREAD

**Issue by azwirko** [pavel-demin/red-pitaya-notes#629]
Hi Pavel,
  Question...I was wondering if your multi-band WSPR receiver/decoder could be converted into a multi-band FT8 receiver/decoder.  I see you use 'wsprd' to decode captured audio.  I think there is an equivalent 'ft8d' here

https://sourceforge.net/p/wsjt/wsjt/7724/tree//branches/wsjtx/lib/fsk4hf/ft8d.f90 

as part of the new WSJT-X 1.8.0 suite of software.  FT8 mode is similar in that it is used on single narrow band (2.5 khz) wide channels across the HF bands.  Timing is much quicker than WSPR though, only 15 secs sequences, so I'm not sure this mode could be setup to run in a similar fashion as your current WSPR code.  Like the WSPR reporting network wsprnet.org, there is a reporting network for FT8 and other digital modes at http://pskreporter.info that I would like to feed data into if possible.  If you could provide code for this, great! If you don't care to attempt coding, could you please comment on whether or not you think this is doable and I may try to learn your software to attempt myself.  

Thanks for a great suite of software!  I've used many of your apps on my Redpitaya.

73

andyz - K1RA
http://k1ra.us/

**Comment by pavel-demin** [comment]
I don't think that I'm going to implement a multi-band FT8 receiver for Red Pitaya.

BTW. The HEAD branch contains a more recent version of the FT8 decoder:

https://sourceforge.net/p/wsjt/wsjt/HEAD/tree/branches/wsjtx/lib/ft8/

> ... could you please comment on whether or not you think this is doable and I may try to learn your software to attempt myself.

Before doing any coding, I'd suggest you to build and to run the FT8 decoder on Red Pitaya and to see how fast it decodes the FT8 messages.

Some FT8 .wav files can be found at the following links:

https://sourceforge.net/projects/wsjt/files/samples/FT8/
https://hamapps.groups.io/g/Support/topic/5501979
https://www.dropbox.com/sh/busdna76pjavht7/AAAXLDcC1sOfarmeLWsMU5vBa?dl=0
