### ISSUE TITLE
QAM in GNU radio with Red Pitaya

### ISSUE THREAD

**Issue by sabine95** [pavel-demin/red-pitaya-notes#630]
### Description of the setup:

 * Device: Red Pitaya
 * SD card image: Red Pitaya for Gnuradio
 * Application: GnuRadio
 * Other relevant information:

### Description of the problem:
Hey,
I've a problem with my Red Pitaya and Gnuradio. I'm using Ubuntu and I installed the Block for the Red Pitaya but when i'm starting a Programm there is no error message but nothing is shown on my oscilloscope.

Im trying to do a Gnuradio Programm and it should QAM and PSK playing and shown them on the oscilloskope.
Is there any solution for it I dont know?

Please help!

Sabine

(sry for my bad english :) )

**Comment by pavel-demin** [comment]
I think that you need to enable PTT in the Red Pitaya sink block

**Comment by sabine95** [comment]
Thank you so much!!
