### ISSUE TITLE
Different signal levels in RX1 and RX2

### ISSUE THREAD

**Issue by davidhay45** [pavel-demin/red-pitaya-notes#636]
### Description of the setup:

 * Device:
 * SD card image: red-pitaya-alpine-3.6-armhf-20171025
 * Application: SDR receiver compatible with HPSDR
 * Other relevant information: Windows 10 wired to RP 

### Description of the problem:
The signal levels of RX1 and RX2 are 3 to 5db different, RX2 is lower.  Why is that?

### Steps to reproduce the problem:

 1. Tune RX1 and RX2 to the same frequency.  Set all other controls the same (ATT, SQL, AGC etc)
 2.
 3.

**Comment by dl1sdz** [comment]
Check the jumpers from input 1 and 2

73 de

Hajo dl1sdz

---
Cela est bien dit, mais il faut cultiver notre jardin.


http://hajos-kontrapunkte.blogspot.de/



Am 26.11.2017 4:20 nachm. schrieb "davidhay45" <notifications@github.com>:

**Comment by pavel-demin** [comment]
> Application: SDR receiver compatible with HPSDR
> The signal levels of RX1 and RX2 are 3 to 5db different, RX2 is lower. Why is that?

Can't reproduce this problem.

Here is a screenshot showing RX1 and RX2:

![rx1_rx2](https://user-images.githubusercontent.com/8037893/33243285-7b037c42-d2e3-11e7-9dd8-eaf008452551.png)

SDR receiver compatible with HPSDR is running in the default configuration with both RX1 and RX2 connected to IN1.

**Comment by davidhay45** [comment]
I can't reproduce it now.  If I see it again I will take a screen shot.

Thanks for looking.

**Comment by davidhay45** [comment]
I think I am confused as to how to map RX1 and RX2 to IN1, how is it done please?

**Comment by pavel-demin** [comment]
It can be done by editing the last line in [apps/sdr_receiver_hpsdr/start.sh](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_receiver_hpsdr/app/start.sh).

The sdr-receiver-hpsdr server has eight command line arguments. Each argument is the input number (1 or 2) corresponding to each of the eight receivers.
