### ISSUE TITLE
Order the red pitaya SDR Kit

### ISSUE THREAD

**Issue by samlo20** [pavel-demin/red-pitaya-notes#656]
Hi Pavel PA3ANG,
I'm Sam with a UK radio callsign M0IDJ, I wonder where can I order your assembled kit, as it states it is £175? or should I order a Red Pitaya SDR Kit, and then follow the building instructions to build the same kit as you have?

Regards,
Sam

**Comment by pavel-demin** [comment]
Hi Sam,

I'm afraid that you're contacting a wrong person here. I'm Pavel but I'm not PA3ANG. Moreover, I'm not aware of any kit. I just write some software for Red Pitaya as a hobby and share it via this GitHub project.

Best regards,

Pavel
