### ISSUE TITLE
Noise Power Ratio Measurement - Red Pitaya as a Signal Generator

### ISSUE THREAD

**Issue by ptamike** [pavel-demin/red-pitaya-notes#661]
Hi Pavel,

Hope you are well. I have a proposal you may be able to help with.

**Overview**
Measuring the performance of SDR receivers is a subject of some debate and one measure that's attracting attention is Noise Power Ratio (NPR). This is a measure that was used extensively back in the 1960's to measure the performance of communication links that were carrying multi-channel FDM (Frequency Division Multiplex) signals. The test signal comprised a wideband Gaussian noise-source with a single deep (~90dB) notch that was slightly wider than one of the voice channels. The nulled voice channel is monitored whilst the noise power applied to the system is gradually increased. The point at which the idle channel noise floor starts to rise is the measurement point and the ratio between the channel noise floor and the applied noise power is recorded as the NPR.
The measurement technique works well for SDRs as it gives an indication of how well the receiver might perform when receiving a weak signal in amongst lots of stronger signals.

The main problem is generating the wideband noise signal with a narrow (~10kHz 90dB_ notch). In the 60's this was done with crystal filters but a digital approach looks the best way forward today and I wondered if you would be able to use your skills with the Red Pitaya to create a test source. There seems to be two approaches: 1. Generate gaussian noise and pass it through a digital notch filter or 2. Generate a large number of random modulated carriers with a gap in place of the notch.

What do you think?

Regards,

Mike - G4WNC

**Comment by pavel-demin** [comment]
Hi Mike,

I'm not sure if Red Pitaya is capable to generate a 90dB deep notch with its 14-bit DAC.

I think it can be easily tested with GNU Radio and the 'SDR transceiver' application for Red Pitaya.

The GNU Radio configuration should be
```
Noise Source -> High Pass Filter -> Red Pitaya Sink
```

Best regards,

Pavel
