### ISSUE TITLE
HPSDR Transceiver 2nd RX question

### ISSUE THREAD

**Issue by davidhay45** [pavel-demin/red-pitaya-notes#666]
### Description of the setup:

 * Device:
 * SD card image:Alpine 3.6
 * Application:sdr_transceiver_hpsdr
 * Other relevant information: OpenHPSDR mRX PS v3.4.7 on Widows 10

### Description of the problem:
Gain of the second receiver lower by 15 dbm.

Have I got something wrongly configured?

![hpsdr_2recvs](https://user-images.githubusercontent.com/33960957/35094137-5ce8429c-fc3c-11e7-9262-f485e41aeb37.png)

**Comment by pavel-demin** [comment]
Do you have the same signal connected to both inputs (IN1 and IN2) of the Red Pitaya board?

It would be helpful to see a screenshot showing the spectra from both receivers.

**Comment by davidhay45** [comment]
I removed and replaced the jumpers.  The signal levels are shown as the same (-89dbm) but the noise levels are about 10dBm different.  Is this "just" a hardware problem with my IN2?

![image](https://user-images.githubusercontent.com/33960957/35097161-ebc6045e-fc46-11e7-8c01-e57ed0a20e92.png)

**Comment by pavel-demin** [comment]
I don't see the 10dBm difference on you screenshot.

**Comment by davidhay45** [comment]
I am away but will post clearer screenshots on my return.

**Comment by davidhay45** [comment]
What appears to be happening is that the noise floor of the second receiver is 5db lower than the first receiver.  In this case I am running sdr_receiver_hpsdr with RX1 and RX2 using IN1.
 The cursor was on the red line in each case.

![two receivers x](https://user-images.githubusercontent.com/33960957/35299471-56a4e5d0-007d-11e8-9a1e-0d55e462c199.png)
![two receivers p1 and p2](https://user-images.githubusercontent.com/33960957/35299498-6e4cf2f4-007d-11e8-993d-5cc8c1d72a92.png)

**Comment by pavel-demin** [comment]
Thanks for the new screenshots. Now, I see the difference.

However, both RX meters show exactly the same values and the RX1 spectrum is smoother than the RX2 spectrum. So,  I'd say that the display settings are different for RX1 and RX2 and that's why the spectrum levels are shown differently.

Please check the display settings (Setup->Display->RX1 and Setup->Display->RX2).

**Comment by davidhay45** [comment]
There were indeed different and when made the same the 5db level difference disappears.  Why were they different I do not know, I certainly have not modified them.

Anyway, problem solved, thanks.
