### ISSUE TITLE
is it possible to use Red-pitaya board as a hardware and introduce it to Vivado as an development board?

### ISSUE THREAD

**Issue by mohammadrasekh68** [pavel-demin/red-pitaya-notes#668]
hello
Im trying to remove the SD card and attach Jtag cables and use red-pitaya as an normal development board (like ZYBO) . can ca you please explain how can i do that?
1. how should i establish JTAG connection ?
2. how should i introduce it to vivado?
Regards

**Comment by pavel-demin** [comment]
I can't answer these questions.
