### ISSUE TITLE
Creating a Linux bootable image for Red Pitaya

### ISSUE THREAD

**Issue by carlos-e-teixeira** [pavel-demin/red-pitaya-notes#670]
Hi Mr. Pavel!

I'm trying to create my own Linux boot image for my Red Pitaya.

I've already created my hardware platform on Vivado. The corresponding bitstream was generated successfully and I've already exported the hardware to SDK. On SDK, I also created the FSBL ('fsbl.elf').

From now on, I don't know exactly what I have to do. I'm still learning about Linux environment.

If I'm correct, I still need to create the BSP and configure it in order to have the 'U-boot.elf'. In addition, I also need the device tree ('.dtb' file) corresponding to the Red Pitaya. Finally, I need to have 'uImage.bin' and 'uRamDisk.image.gz' files. After having all these files, I think I can create my boot image (.bin) using Bootgen and put it on my SD card.
Is all this correct?

If so, where can I find all these remaining files? Or how can I create them?

I will appreciate any help and/or comments!
Thank you in advance!
Best regards!

**Comment by pavel-demin** [comment]
My scripts that build SD card images are in the [scripts](https://github.com/pavel-demin/red-pitaya-notes/tree/master/scripts) directory.

Some more details can be found in the [LED blinker](http://pavel-demin.github.io/red-pitaya-notes/led-blinker) notes.

**Comment by carlos-e-teixeira** [comment]
Thank you for the answer, Mr. Pavel.
I found that so complex, but I will try to understand it.
At least, is it correct, the process I described?

**Comment by pavel-demin** [comment]
> At least, is it correct, the process I described?

I'm not sure if I understand your description. You can find my description of the process on the page 11 of [this PDF file](https://www.dropbox.com/sh/5fy49wae6xwxa8a/AACl--BhQvcNgjeQLRaiX9dha/ClubVivado2016_Pavel_Demin.pdf?dl=1) and compare it with yours.

**Comment by carlos-e-teixeira** [comment]
No problem!
This document helps me, thank you!
