### ISSUE TITLE
Question about MCPHA

### ISSUE THREAD

**Issue by OCaha** [pavel-demin/red-pitaya-notes#672]
Dear Pavel,
thank you very much for your mcpha code for Redpitaya. We are succesfully using it with our old energy dispersive x-ray detector for x-ray fluorescence; it works nicely.
However, for a better performance I would like to have some "command line style program" under windows  at client side. So, I would like to ask how did you compile it to get windows binary (in which environment), so we can change the source and compile according our needs?
We would like to have some program which can automatically connect to RedPitaya, integrate for a certain time and then save data to a given filename.
Thanks in an advance,
Ondrej Caha
Brno, Czech republic

**Comment by pavel-demin** [comment]
Dear Ondrej,

I'm glad that my mcpha code works for you.

I think that the easiest would be to download a [pre-built Tcl runtime](http://www.ch-werner.de/AndroWish/vanillawish-74a062d634-win64.exe) from the [AndroWish](https://www.androwish.org) project and use it to run your modified version of [mcpha.tcl](https://raw.githubusercontent.com/pavel-demin/red-pitaya-notes/master/projects/mcpha/client/mcpha.tcl) or [pha.tcl](https://raw.githubusercontent.com/pavel-demin/red-pitaya-notes/master/projects/mcpha/client/pha.tcl).

Here is the command to run from the command line:
```
vanillawish-74a062d634-win64.exe mcpha.tcl
```

Another approach would be to write a new command line style program using a different programming language. The control protocol is very simple and can be programmed in any modern programming language,

Best regards,

Pavel
