### ISSUE TITLE
qspectrumanalyzer & soapy_power not working with the SDR transceiver - Ubuntu 16.04

### ISSUE THREAD

**Issue by satfan52** [pavel-demin/red-pitaya-notes#695]
Hello,

I am trying to use the red-pitaya as a spectrum analyser using qspectrumanalyzer & soapy_power as a client to the SDR transceiver but it gives erroneous results in my Ubuntu 16.04 environment. The qspectrumanalyzer application launches ok and the soapy_power sweep starts fine  but the spectrum displayed is very "creative" (to say the least, see picture enclosed).

the parameters I use are: driver=redpitaya, addr=192.168.0.102, port=1001

The problem could be with the SDR transceiver,  qspectrumanalyzer & soapy_power or in my own environment. However since my rtl-sdr dongle works "normally" with qspectrumanalyzer & soapy_power I suspect that the problem is not in my environment. 

In the pictures below, the test signal is at 28Mhz,and  its power is about 10dBm. There is an attenuator of 45 dB between the RP and the signal generator so the power of the input signal received by the RP is in the order of -35dBm. Further attenuating the input signal does not solve the issue. I have also tried setting the gain to 0dB with the option --gain 0 but no improvement either. 

If the problem is not (or not only) with SDR transceiver, my next step will be to report the problem to the developper of the qspectrumanalyzer & soapy_power applications

Regards
Peter

PS: No network throughput issues, I use a dedicated router to handle the traffic between the PC and the RP.

![soapy1](https://user-images.githubusercontent.com/14941529/38762235-6b2e7d44-3f8a-11e8-85f7-1aec210c8fa7.png)
![soapy2](https://user-images.githubusercontent.com/14941529/38762237-6cb07da2-3f8a-11e8-80de-87249a3db6a3.png)
![soapy3](https://user-images.githubusercontent.com/14941529/38762240-6e597104-3f8a-11e8-8e3d-b8f4bfe7b3fa.png)

**Comment by pavel-demin** [comment]
Hello Peter,

Thank you for the screenshots. I'd suggest to set 'Crop [%]' to at least 20.

Best regards,

Pavel

**Comment by pavel-demin** [comment]
I've just tried to run qspectrumanalyzer and I've obtained some reasonably looking spectra with the following settings:
 - sample rate: 1.250 MHz
 - start frequency: 1.000 MHz
 - stop frequency: 50.000 MHz
 - bin size: 1.000 kHz
 - interval: 10 s
 - crop: 20 %

**Comment by satfan52** [comment]
Dear Pavel,

Thanks for your reply. I understand your point about cropping (20%) and setting a larger interval (10s). However it does not solve the issue. I have tried the very same settings that you did (see pictures) and in my ubuntu 16.04 environment, the spectra produced displays additional non-existing spurs  at roughly 29 Mhz and 42 Mhz. Those spurs are not minor ones, they are of the same power than the existing real ignals at 28Mhz at 41 Mhz!. It just impossible to use soapy_power and the SDR transceiver to make some reasonably accurate spectra measurements. 

Please have at the picture below that compare the spectra obtained using osmocom-fft and soapy_power...
 
![qs28mhz](https://user-images.githubusercontent.com/14941529/38768236-9b9ef3e4-3ff0-11e8-91b0-a28a9c828fb8.png)
![osmo41mhz](https://user-images.githubusercontent.com/14941529/38768239-9d6ad260-3ff0-11e8-8efe-4fc7620d5340.png)
![osmo28mhz](https://user-images.githubusercontent.com/14941529/38768240-9e9a96de-3ff0-11e8-92c9-e8b919d83d61.png)
   
Best Regards
Peter

**Comment by pavel-demin** [comment]
The problem of multiple peaks can be solved by adding `--tune-delay 0.1` to the 'Additional parameters' field in the 'Settings' window.

**Comment by pavel-demin** [comment]
Here is a screenshot showing my settings:
![qspectrumanalyzer](https://user-images.githubusercontent.com/8037893/38769413-1bbd67c4-4003-11e8-95c6-f779e98ae5aa.png)

**Comment by satfan52** [comment]
Yes !!! 
This solves the issue.
I would have never thought about changing this parameter!!!
Thanks :-)
