### ISSUE TITLE
Confusion on Install of GNURadio for Red Pitaya

### ISSUE THREAD

**Issue by TravisAutry** [pavel-demin/red-pitaya-notes#720]
Hi Pavel,

First thank you for building up the SDR capabilities of the red Pitaya.  I am trying to get GNURadio up and running and I am running into some issues.  I have followed the instructions here http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver/ .

### Description of the setup:
- I have Alpine up and running on the red-pitaya using your image.
- I am using a Mac (I think this might be my issue).
- I can ssh in and I installed gnuradio for mac via macports as found https://wiki.gnuradio.org/index.php/MacInstall

### Description of the problem:

On the last step of your instructions you say to do 

export GRC_BLOCKS_PATH=.gnuradio-companion trx_ssb.grc

but I get the error
-bash: export: `trx_ssb.grc': not a valid identifier

I am having a tough time figuring out what this command is supposed to do or if it is appropriate for my mac. 

-  I can see all of your code and I can open your .grc files in gnu-radio companion.
- In gnu-radio companion I get the errors 
      Block key "red_pitaya_source" not found
      Block key "red_pitaya_sink" not found

I was wondering if you might have any insight as to what I am doing wrong/ steps I can take to tell gnuradio where your files are as I am unfamiliar with both gnuradio and your code.

Thanks so much,
Travis

**Comment by pavel-demin** [comment]
> On the last step of your instructions you say to do
> export GRC_BLOCKS_PATH=.gnuradio-companion trx_ssb.grc

Why are you putting the two separate commands together on a single line?

I've just checked the instructions at [this link](http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver/#getting-started-with-gnu-radio) and they are shown as three separate lines:
```
cd red-pitaya-notes/projects/sdr_transceiver/gnuradio
export GRC_BLOCKS_PATH=.
gnuradio-companion trx_am.grc
```
