### ISSUE TITLE
[BD 5-390] IP definition not found for VLNV: pavel-demin:user:axis_red_pitaya_dac:1.0 

### ISSUE THREAD

**Issue by cleverlau** [pavel-demin/red-pitaya-notes#737]
Hello, I am very sorry to bother you,pavel.

 I always get this error when I run your dac_test project in the TCL console. Why?
"[BD 5-390] IP definition not found for VLNV: pavel-demin:user:axis_red_pitaya_dac:1.0 
"
best regards
Cong

**Comment by pavel-demin** [comment]
Please provide more information about your setup and about the commands that you're typing in the Tcl console.

If you're not using the Makefile, then the correct commands to be used in the Tcl console can be found in https://github.com/pavel-demin/red-pitaya-notes/issues/722#issuecomment-414821554.
