### ISSUE TITLE
rx1 bandpassfilter by i2c adress 0X21

### ISSUE THREAD

**Issue by fransnissen** [pavel-demin/red-pitaya-notes#768]
### Description of the setup:

 * Device: Hamlab (redpitaya)
 * SD card image: latest 21 juli 2017
 * Application: powersdr charly 25 hamlab
 * Other relevant information:

### Description of the problem:
Hi, i have a hamlab (redpitaya) i'm build a RX BPF into the the hamlab tru teh i2c interface with a PCA9555 ic to improve the ham band reception. the problem i discovert is that  the switch frequentie from the pca9555 outputs are at the edge from the hambands.

so my question, is it possible to change the frequentie where the pca9555 switched. i want to build a rx bpf where the top bpf frequentie is the beginning from the second band.

1,8mhz - 2,5hmz
2,5hmz - 6mhz ectect...

### Steps to reproduce the problem:

 1. non no idee
 2.
 3.

**Comment by pavel-demin** [comment]
As far as I know, it's the software (PowerSDR mRX PS) running on PC that decides when to switch PCA9555 at address 0x21.

It's possible to modify [sdr-transceiver-hpsdr.c](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c) and to change this behavior.

The [code at lines 913-935]https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c#L913-L935) runs when the RX1 frequency changes. It's possible to add some code that would compare the RX1 frequency with the edges of the hambands and that would send commands to a chip connected to the I2C bus.
