### ISSUE TITLE
FT8 dcoder antenna change from IN1 to IN2

### ISSUE THREAD

**Issue by sq3rx** [pavel-demin/red-pitaya-notes#773]
Hi Pavel,
Can you explain how to change antenna IN1 to IN2 for FT8 decoder ?

**Comment by pavel-demin** [comment]
The input is selected by the `chan` parameter in [write-c2-files.cfg](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_ft8/app/write-c2-files.cfg).
