### ISSUE TITLE
The new FT8+ version of the original software by Joe Taylor - backwards incompatible

### ISSUE THREAD

**Issue by waterwin** [pavel-demin/red-pitaya-notes#787]
Are there plans to update the current Alpine release to be compatible with WSJT-X 2.0?

I have written software to use both antenna inputs and a score of different frequency band configuration files to monitor FT8 activity in a Day-Night rhytm with 2 antennas. 

As soon as the majority of the users move from version 1.9 or older to 2.0 the FT8 decoder in the current version becomes obsolete.

de PE3ES, Erwin, technical writer for VERON/Electron and FUNKAMATEUR

https://www.dropbox.com/s/4fatzgbrr0xhp8s/.c2%20files%20for%2077%20bits%20upgrade.zip?dl=0

See link for a set of .c2 files

**Comment by pavel-demin** [comment]
There is already an open issue about the FT8 protocol. I don't see why we need another one.

Thanks for the .c2 files. I've downloaded them.
