### ISSUE TITLE
support for more than 8 hpsdr receivers

### ISSUE THREAD

**Issue by ahopper** [pavel-demin/red-pitaya-notes#791]
Hi, I've just released a version of [SparkSDR](http://www.ihopper.org/radio/latest-beta.htm) that has receive support for the 8 rx HPSDR code. It can receive multiple modes simultaneously on each receiver. I wondered if it was possible to add a few extra receivers using the extensions to the HPSDR protocol used by the hermes lite https://github.com/softerhardware/Hermes-Lite2/wiki/Protocol.

**Comment by pavel-demin** [comment]
Hi Alan,

At the moment, I don't know how to add more receivers to the SDR receiver compatible with HPSDR. The current version uses 90% of the DSP blocks available on the FPGA.

However, the recently announced [STEMlab 122.88-16 SDR](https://www.redpitaya.com/n86/new-stemlab-sdr) board will have more FPGA resources and it'll be possible to double the number of receivers when this new board becomes available.

Best regards,

Pavel

**Comment by SM6FMB** [comment]
Hi Pavel!

I have earlier sent above question to Allan!

It's really sad that you can't have possiblity to have all 11 HF band covered in one RP!
As a power monitor station I would like to cover all HF bands in one RP.

I do not buy a new  RP for this purpose! I have already 2 pcs of RP.

73 de Sven SM6FMB

**Comment by ahopper** [comment]
Hi Parvel,
the new board sounds interesting and I hope I can support that in Spark. There is some ongoing work in the Hermes Lite group to squeeze more receivers into limited fpga space, maybe some of this development can be shared. Many thing have been discussed, doing the fir on the pc, doing the lower cic stages sequentially rather than in parallel, alternatives to the cordic and much more.

Best Regards
Alan
