### ISSUE TITLE
idiots guide

### ISSUE THREAD

**Issue by jeffforber** [pavel-demin/red-pitaya-notes#818]
### Description of the setup

Windows 10 ....no linux pc 

 * Device: redpitaya 125-14 
 * SD card image: red-pitaya-alpine-3.9-armv7-20190215.zip
 * Application:
 * Other relevant information:   i have the hdsdr and power sdr working ok ....iam 75 and  i have no programing skills  ok with a raspberry -pi copy and paste ........ unpacked the file with 7zip   ,,when i tried to flash program it says no .img  so i just copied and pasted the file to the sd card 
  i put my call sign and grid location and copied the start file too the first dir 

### Description of the problem

i followed your instuctions but the green led is only on .... ...i get rp is ready for wspr message but no other leds light up .....  i hope this is enough info .........  i want to use wspr and ft8 rx.... i would really like a step by step idiots guide please 
 regards jeff  TA4/G8SCU

**Comment by pavel-demin** [comment]
> when i tried to flash program it says no .img so i just copied and pasted the file to the sd card

All the files from and directories should be copied from the .zip file to a SD card.

> i put my call sign and grid location

What text editor are you using to edit decode-wspr.sh?

**Comment by jeffforber** [comment]
Windows note pad

On 23 Mar 2019 19:55, Pavel Demin <notifications@github.com> wrote:

when i tried to flash program it says no .img so i just copied and pasted the file to the sd card

All the files from and directories should be copied from the .zip file to a SD card.

i put my call sign and grid location

What text editor are you using to edit decode-wspr.sh?

**Comment by jeffforber** [comment]
Do you need to extract the files??

**Comment by pavel-demin** [comment]
> Do you need to extract the files?

Yes, you need to extract all the files and directories from the .zip file to a SD card.

**Comment by pavel-demin** [comment]
I think that the editor that you used to edit decode-wspr.sh replaced the Unix end-of-line characters with the Windows end-of-line characters.

I'd suggest to use an editor that doesn't change the end-of-line characters. For example, Notepad++:

https://notepad-plus-plus.org

Since it starts to be a recurrent problem, I've just tried to add a workaround of this problem to my scripts. Here is a link to a .zip file that contains this workaround: 

https://www.dropbox.com/sh/5fy49wae6xwxa8a/AADmGGMgiQrRUOAM1LYE41Mna/red-pitaya-alpine-3.9-armv7-20190323.zip?dl=1

Could you try to download and install this new version?

**Comment by jeffforber** [comment]
Ok thank you for getting back so quickly i will try this .advice

On 23 Mar 2019 21:19, Pavel Demin <notifications@github.com> wrote:

I think that the editor that you used to edit decode-wspr.sh replaced the Unix end-of-line characters with the Windows end-of-line characters.

I'd suggest to use an editor that doesn't change the end-of-line characters. For example, Notepad++:

https://notepad-plus-plus.org

Since it starts to be a recurrent problem, I've just tried to add a workaround of this problem to my scripts. Here is a link to a .zip file that contains this workaround:

https://www.dropbox.com/sh/5fy49wae6xwxa8a/AADmGGMgiQrRUOAM1LYE41Mna/red-pitaya-alpine-3.9-armv7-20190323.zip?dl=1

Could you try to download and install this new version?

**Comment by jeffforber** [comment]
Hello Pavel.....i have tried that latest version. Plus i used a different sd card its not working just a solid green led.

On 23 Mar 2019 21:19, Pavel Demin <notifications@github.com> wrote:

I think that the editor that you used to edit decode-wspr.sh replaced the Unix end-of-line characters with the Windows end-of-line characters.

I'd suggest to use an editor that doesn't change the end-of-line characters. For example, Notepad++:

https://notepad-plus-plus.org

Since it starts to be a recurrent problem, I've just tried to add a workaround of this problem to my scripts. Here is a link to a .zip file that contains this workaround:

https://www.dropbox.com/sh/5fy49wae6xwxa8a/AADmGGMgiQrRUOAM1LYE41Mna/red-pitaya-alpine-3.9-armv7-20190323.zip?dl=1

Could you try to download and install this new version?

**Comment by jeffforber** [comment]
I will try the note pad ++

On 23 Mar 2019 21:19, Pavel Demin <notifications@github.com> wrote:

I think that the editor that you used to edit decode-wspr.sh replaced the Unix end-of-line characters with the Windows end-of-line characters.

I'd suggest to use an editor that doesn't change the end-of-line characters. For example, Notepad++:

https://notepad-plus-plus.org

Since it starts to be a recurrent problem, I've just tried to add a workaround of this problem to my scripts. Here is a link to a .zip file that contains this workaround:

https://www.dropbox.com/sh/5fy49wae6xwxa8a/AADmGGMgiQrRUOAM1LYE41Mna/red-pitaya-alpine-3.9-armv7-20190323.zip?dl=1

Could you try to download and install this new version?

**Comment by pavel-demin** [comment]
> Plus i used a different sd card its not working just a solid green led.

I don't see any problem with the solid green LED. It was once requested to disable the blinking LEDs in my applications to reduce the noise level.

**Comment by pavel-demin** [comment]
I see that your multiband spots start to appear in the wsprnet.org fatabase. So, the WSPR application works.

**Comment by jeffforber** [comment]
Yes i see now its working ...fantastic.

On 23 Mar 2019 21:51, Pavel Demin <notifications@github.com> wrote:

I see that your multiband spots start to appear in the wsprnet.org fatabase. So, the WSPR application works.

**Comment by jeffforber** [comment]
Tomorrow i will try Ft8 ...thank you very much ....rrgards jeff

On 23 Mar 2019 21:51, Pavel Demin <notifications@github.com> wrote:

I see that your multiband spots start to appear in the wsprnet.org fatabase. So, the WSPR application works.
