### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by jeffforber** [pavel-demin/red-pitaya-notes#820]
### Description of the setup:

 * red-pitaya-alpine-3.9-armv7-20190323.zip
 * Application:idiots gude
 * Other irrelevant information:   hello Pavel another request please .....i can not believe how well this little box of tricks works, i wish i had a fraction of the brain you have .....you are a genius .....i have opened  the terminal and changed password ok ...now what what to do next is the problem.......i can only copy and paste 

### Description of the problem:                                           
 as a complete newbie/idiot...how to change bands using SSH.....????

**Comment by pavel-demin** [comment]
Here are the instructions:
- connect to Red Pitaya following the instructions from the Red Pitaya documentation:
https://redpitaya.readthedocs.io/en/latest/developerGuide/os/ssh/ssh.html
- make SD card writable
```
rw
```
- edit write-c2-files.cfg
```
nano apps/sdr_transceiver_wspr/write-c2-files.cfg
```
- make SD card read-only
```
ro
```

**Comment by jeffforber** [comment]
Thank you very much for the quick response....regards jeff

On 27 Mar 2019 17:35, Pavel Demin <notifications@github.com> wrote:

Here are the instructions:

  *   connect to Red Pitaya following the instructions from the Red Pitaya documentation:
https://redpitaya.readthedocs.io/en/latest/developerGuide/os/ssh/ssh.html
  *   make SD card writable

rw


  *   edit write-c2-files.cfg

nano apps/sdr_transceiver_wspr/write-c2-files.cfg


  *   make SD card read-only

ro
