### ISSUE TITLE
Makefile execution is repeating itself indefinitely 

### ISSUE THREAD

**Issue by ssooffiiaannee** [pavel-demin/red-pitaya-notes#828]
### Description of the setup:

 * Device: Red Pitaya
 * SD card image:
 * Application: led blinker project
 * Other relevant information: working on debian 8.11 and using vivado 2018.3

### Description of the problem:
In the led blinker tutorial, I execute de command make NAME=led_blinker all, and I get stuck 
in a loop that restarts undifinitely, I'm working on it for the past days, and I'm still stuck on it.

### Steps to reproduce the problem:
after installing vivado: 
 1.source /opt/Xilinx/Vivado/2018.3/settings64.sh
 2.git clone https://github.com/pavel-demin/red-pitaya-notes
cd red-pitaya-notes
 3.make NAME=mcpha bit

**Comment by pavel-demin** [comment]
What operation is repeated? Why do you think that Makefile execution is repeating itself indefinitely? Could you provide some log or screenshot illustrating the problem?

**Comment by ssooffiiaannee** [comment]
I installed vivado
In Red Pitaya notes, In the led blinker, I executed the following commands : 
![Capture](https://user-images.githubusercontent.com/37119086/56222123-c2f34200-606b-11e9-8989-95a037f12d6b.PNG)
 
Then I get the following result that is repeating  (it's not the whole result I put in this image, since I cannot put everything in on single image )
![Capture1](https://user-images.githubusercontent.com/37119086/56222474-65132a00-606c-11e9-94f1-9cc108cb9980.JPG)

**Comment by ssooffiiaannee** [comment]
Could you tell me what is the next step in Build SD card image zip file, in mcpha project?

<img width="627" alt="Capture" src="https://user-images.githubusercontent.com/37119086/56224264-9c370a80-606f-11e9-8bdb-4ec26cc5a265.PNG">

**Comment by pavel-demin** [comment]
Thanks for the screenshot.

When you run the make command for the first time, it's normal that it runs the `core.tcl` script multiple times. The `core.tcl` script is used to build the IP cores from the sources that can be found in the [cores](https://github.com/pavel-demin/stemlab-sdr-notes/tree/master/cores) directory. Since there are 49 IP cores in the [cores](https://github.com/pavel-demin/stemlab-sdr-notes/tree/master/cores) directory, the `core.tcl` script is executed 49 times.

**Comment by pavel-demin** [comment]
The `build-all.sh` script does the following:
 - builds the IP cores
 - builds led_blinker.bit
 - builds Linux
 - builds U-Boot
 - builds all the projects that I normally put on my SD card images
 - builds a SD card image based on Alpine Linux

**Comment by ssooffiiaannee** [comment]
Thank you for your reply
My first question is: Do I have to write my SD card after this command or is it automatically done ?
My second one : Do I have to insert the SD card while executing this command?

**Comment by pavel-demin** [comment]
The `build-all.sh` creates a zip file. The content of the zip file should be copied manually to an SD card. It's the same zip file as linked from the 'Getting started' instructions.

**Comment by ssooffiiaannee** [comment]
I actually have 2 partitions on my SD card, to which partition shall I copy it?

In the led blinker tutorial, what does this command do? because I don't have mmcbl0 in the dev directory, even after inserting my SD card

![Screenshot from 2019-04-16 22-29-38](https://user-images.githubusercontent.com/37119086/56241871-3f4f4a80-6097-11e9-83a4-efd19d9a434b.png)

**Comment by pavel-demin** [comment]
I normally use a SD card with a single FAT formatted partition. It's how most of the SD cards are formatted out of the box.

The command does exactly that is written: builds a bootable SD card. Where `/dev/mmcblk0` is the path to the SD card. If you don't have it then skip this command and try the next one that builds a SD card image that can be later copied to a SD card.
