### ISSUE TITLE
Red Pitaya + GNU Radio | Loopback baseband/passband | corruption after few secs

### ISSUE THREAD

**Issue by fmagno** [pavel-demin/red-pitaya-notes#832]
### Description of the setup:

 * Device: **STEMLAB 125-14**
 * SD card image: **red-pitaya-alpine-3.9-armv7-20190215.zip**
 * Application: **GNU Radio**
 * Other relevant information: **(please find below)**

### Description of the problem:
Hi Pavel,

Thanks for taking the time to look into this. Follows my question:

Running the following GNU Radio flowgraph ([gr_baseband_async_oi.grc](https://raw.githubusercontent.com/fmagno/dsp/master/dsp/transmission/gr_baseband_async_oii.grc)):
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3079603/56423856-d5f15680-62a5-11e9-939a-0352d1f0dd9e.png">

With OUT1 connected to IN1 and IN2 as depicted below:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/3079603/56424048-8a8b7800-62a6-11e9-87d0-6470bc6407c8.png">

And by transmitting the following input signal ([sig_input.dat](https://filebin.ca/4eEaZDUT2ne8/r050000_f000001.0_d0_g0_a1.0_n010_u1_p0.1.dat)):
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3079603/56424313-9f1c4000-62a7-11e9-91ec-dcc439529bdd.png">

- samp_rate: 50000
- freq: 1 Hz
- amplitude: 1.0
- duration: 500000 (10 periods) - 10 secs

Then produced the following received signals generated after 10 runs (each run with a different colour):

PORT IN1:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3079603/56424576-c0c9f700-62a8-11e9-8954-61b90f557eb4.png">

PORT IN2:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/3079603/56424579-c7f10500-62a8-11e9-8702-fee06059aa10.png">

Apparently the signals arrive correctly (ignoring the amplitude attenuation) for ~2 secs but then they start showing artefacts/corruption.
A few more pictures in detail:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/3079603/56424723-68472980-62a9-11e9-8364-fb8dd3d418a7.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/3079603/56424747-7dbc5380-62a9-11e9-9f0b-ad050098c346.png">

Among other tests I have also tried a similar flowgraph with a different center_freq but similar corruption arises:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/3079603/56425004-6fbb0280-62aa-11e9-85d1-c1a6dbe70f0b.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3079603/56425021-7e091e80-62aa-11e9-8dfa-7d9427b9c28b.png">

I wonder if you can reproduce this behaviour and whether this is expected?
Let me know if more info is needed.

Thanks in advance,
fmagno

**Comment by pavel-demin** [comment]
Thanks for providing very detailed description of your setup and for sharing all the scripts.

I've just tried to run your grc configuration 10 times and here are the output plots showing 10 recorded signals:
![out1x10](https://user-images.githubusercontent.com/8037893/56439114-4c617900-62e5-11e9-87c3-82839b2e37db.png)
![out2x10](https://user-images.githubusercontent.com/8037893/56439118-4e2b3c80-62e5-11e9-8d6a-3edcc5e669f1.png)

I've set the sample rate to 50k and the duration to 500k. My setup has 50 Ohm terminators on both inputs.

**Comment by fmagno** [comment]
Thanks a lot for your quick reply! Although the 50 Ohm did not make any difference on my setup, what really made a huge difference was adding the other Red Pitaya Sink and drive it with a Constant Source with 0's - image below:

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/3079603/56447579-fe5a6e80-6300-11e9-8e3b-859f4e6e46b3.png">

I even ran the experiment for a while longer and it seems to be running just fine:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/3079603/56447597-234ee180-6301-11e9-8bc3-3330b8b3f48d.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/3079603/56447601-2a75ef80-6301-11e9-98e8-d111929faf56.png">

I am now left wondering why you weren't able to reproduce the same issue on your setup?

**Comment by fmagno** [comment]
Sandly enough that was a rushed conclusion because apparently, yesterday, I was not able to reproduce the issue with the new changes after a few trials but today the issues still show up.
I am also running the experiments for a longer period (20 secs). I have concluded that both inputs behave in the same way so I'm just going to show plots of one of them for the same of simplicity. This is what I have so far:

Exp 1:

- With the second Red Pitaya Sink disabled
- With 50 Ohm terminators on both inputs

<img width="566" alt="image" src="https://user-images.githubusercontent.com/3079603/56455003-25d92780-6351-11e9-897b-4ba8da790e83.png">
<img width="568" alt="image" src="https://user-images.githubusercontent.com/3079603/56455009-36899d80-6351-11e9-935e-1f49c8b27da0.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/3079603/56455043-9f711580-6351-11e9-82b7-fee16f2150bf.png">
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/3079603/56455050-be6fa780-6351-11e9-8c20-f6216f0ae287.png">


Exp 2:

- With the second Red Pitaya Sink driven by Constant Source with 0's
- With 50 Ohm terminators on both inputs
<img width="570" alt="image" src="https://user-images.githubusercontent.com/3079603/56455143-ddbb0480-6352-11e9-8939-5b08181ef067.png">

Exp 3:

- With the second Red Pitaya Sink disabled.
- Without 50 Ohm terminators on inputs

<img width="565" alt="image" src="https://user-images.githubusercontent.com/3079603/56455301-89188900-6354-11e9-8ced-94dccd583e08.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/3079603/56455335-ced55180-6354-11e9-8923-6b6709af7e7d.png">

Exp 4:

- With the second Red Pitaya Sink PTT set to `false`
- Without 50 Ohm terminators on inputs

<img width="571" alt="image" src="https://user-images.githubusercontent.com/3079603/56455387-84a0a000-6355-11e9-8624-8bf0318208bb.png">
<img width="561" alt="image" src="https://user-images.githubusercontent.com/3079603/56455570-d1857600-6357-11e9-81f5-738ed209f5d4.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/3079603/56455677-355c6e80-6359-11e9-9c4e-64c35ef2dc76.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/3079603/56455697-ab60d580-6359-11e9-8f95-aac200b1ccb6.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3079603/56455741-3346df80-635a-11e9-8394-102abbc4a3dd.png">


Exp 5:

- With the second Red Pitaya Sink PTT set to `false`
- With 50 Ohm terminators on inputs

<img width="568" alt="image" src="https://user-images.githubusercontent.com/3079603/56455813-748bbf00-635b-11e9-8291-81bdc8778631.png">
<img width="584" alt="image" src="https://user-images.githubusercontent.com/3079603/56455844-e237eb00-635b-11e9-960e-e994dcba2693.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/3079603/56455879-64281400-635c-11e9-8886-5e5fce93340b.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/3079603/56455911-d4369a00-635c-11e9-91de-fa70e7371ea3.png">



Remarks:

There seems to be a random effect which is positively biased if the second output is driven with data (e.g 0's) or if the PTT parameter is set to `False`, however the corruption still shows up way too frequently.

Are you not able to reproduce this issue in any of these experiments?

Cheers!

**Comment by pavel-demin** [comment]
The second plot shows that one of the recorded signals has a lower frequency. So, the TX or RX samples were somehow delayed. I'd suspect on of the following:
- network connection problem (bad cables, slow routers, slow network interfaces, Wi-Fi)
- slow computer running GNU Radio (virtual machine, ARM CPU)

**Comment by fmagno** [comment]
I ran the above experiments with two modern machines, both with a direct wired connection to the Red Pitaya:
- MacBook Pro:
    - macOS Mojave 10.14.4
    - CPU: Intel Core i7 2.9GHz
    - Intel HD Graphics 530 1536 MB
    - Memory: 16GB
    - NIC: belkin USB-C to Ethernet Adapter F2CU040 (Gigabit)
    - GNU Radio Companion 3.7.12.0

- Insys:
    - Ubuntu 19.04
    - Intel Core i7-8750H CPU @ 2.20GHz × 12
    - GeForce GTX 1070 with Max-Q Design/PCIe/SSE2
    - kernel: 5.0.0-13-generic x86_64 x86_64 x86_64 GNU/Linux
    - NIC: Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
    - GNU Radio Companion 3.7.13.4

Both setups show similar corruption but, with the Ubuntu setup, sometimes an error occurs with the following message:
    - "file_descriptor_sink: Broken pipe"
And when this happens the received signal looks like this:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/3079603/56468678-65724300-6427-11e9-9f53-2c1539111ff0.png">

I believe this error has nothing to do with the corruption. Looks like a different thing...
The coaxial cables are in good condition.

Do you have a suggestion on how this can be debugged?

I wonder if you have come across the need of implementing a loopback test application that would run inside the Red Pitaya, like the sdr_transceiver, and would not require communication with an SDR running on a computer. It would just transmit a sine wave already stored in the SD card and would then store the received signal (implying that the IN and OUT ports would be physically connected for the test to make sense). We could then compare the signals offline.

**Comment by pavel-demin** [comment]
My GNU Radio test machine is much less powerful than your systems. My test machine is a small netbook with AMD E2-1800 CPU, Ubuntu 16.04 and GNU Radio 3.7.10.

> Do you have a suggestion on how this can be debugged?

I think that the first step should be to understand what part of the signal processing chain doesn't work. I'd check the TX signal using an external oscilloscope and I'd check the RX part using an external signal generator.

**Comment by fmagno** [comment]
Hi Pavel,

Thanks for the suggestion.
Follows a set of experiments that show the issue for different combination of parameters.
Exp 1

Here's a simpler flowgraph that shows the issue for different sample rates:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/3079603/56508298-c24f2580-651b-11e9-9ccc-eb9cc1a3f22b.png">

20K
<img width="849" alt="image" src="https://user-images.githubusercontent.com/3079603/56508737-f9720680-651c-11e9-9f56-fed448d94651.png">

50K
<img width="847" alt="image" src="https://user-images.githubusercontent.com/3079603/56508751-00007e00-651d-11e9-987b-c9e685662d6d.png">

100K
<img width="850" alt="image" src="https://user-images.githubusercontent.com/3079603/56508769-0858b900-651d-11e9-91ab-dd08bc83d38d.png">

250K
<img width="845" alt="image" src="https://user-images.githubusercontent.com/3079603/56508783-127ab780-651d-11e9-8f37-9cae2c461b9b.png">

500K
<img width="850" alt="image" src="https://user-images.githubusercontent.com/3079603/56508788-18709880-651d-11e9-9262-4697643e73c4.png">

1.25M
<img width="842" alt="image" src="https://user-images.githubusercontent.com/3079603/56508798-1eff1000-651d-11e9-81be-ab266607ffc4.png">

Surprisingly the output with the best result is the one with higher sample rate (1.25M).

Exp2

Now with both OUT ports:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/3079603/56509662-8027e300-651f-11e9-9454-fb6283246458.png">

20K
<img width="853" alt="image" src="https://user-images.githubusercontent.com/3079603/56509682-8ddd6880-651f-11e9-9436-2ae76bc09b36.png">

50K
<img width="841" alt="image" src="https://user-images.githubusercontent.com/3079603/56509690-933ab300-651f-11e9-9617-f2be13d6d0de.png">

100K
<img width="840" alt="image" src="https://user-images.githubusercontent.com/3079603/56509700-9afa5780-651f-11e9-924b-fd4ecedab339.png">

250K
<img width="846" alt="image" src="https://user-images.githubusercontent.com/3079603/56509713-a2b9fc00-651f-11e9-8360-dac6cd9c3af8.png">

500K
<img width="847" alt="image" src="https://user-images.githubusercontent.com/3079603/56509728-abaacd80-651f-11e9-85f5-6ffb276d4dc3.png">

1.25M
<img width="849" alt="image" src="https://user-images.githubusercontent.com/3079603/56509743-b1a0ae80-651f-11e9-85e5-b9a430b16a50.png">

It still shows better results for higher sample rates.


Exp3

Now, with IN1 enabled:

20K
<img width="903" alt="image" src="https://user-images.githubusercontent.com/3079603/56510636-43a9b680-6522-11e9-9797-ac3ac6525e57.png">

50K
<img width="907" alt="image" src="https://user-images.githubusercontent.com/3079603/56510647-4f957880-6522-11e9-9802-0fcc98d3c4d1.png">

250K
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/3079603/56510691-75228200-6522-11e9-9214-46482d78604b.png">

1.25M
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/3079603/56510715-8c616f80-6522-11e9-8aba-2107f0386191.png">


Ex4

With both inputs enabled:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/3079603/56511029-71432f80-6523-11e9-8978-1ef85490109f.png">

1.25M
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/3079603/56511064-8b7d0d80-6523-11e9-9569-af2fc52c7c53.png">

Blue and green are the real components of the received signals.
Red and orange are the imaginary components and are always 0 as expected.


Exp5
With IN1 and OUT1. Still, IN1 is being driven by a signal generator and OUT1 is being measured with the oscilloscope. Flowgraph:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/3079603/56511920-ca13c780-6525-11e9-8ec3-595cfefc5915.png">

Ran this experiment with 500K for 20 secs and with 1.25M for 80 secs:

500K
<img width="854" alt="image" src="https://user-images.githubusercontent.com/3079603/56512001-00e9dd80-6526-11e9-97c8-b76103a054cd.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/3079603/56512042-21199c80-6526-11e9-9dbe-9e36d602ccf5.png">

The output signal looks good up until the 10th second and then it gets corrupted. It never recovers the correct wave shape.

1.25M
[0-40] sec
<img width="848" alt="image" src="https://user-images.githubusercontent.com/3079603/56512544-989bfb80-6527-11e9-9d30-77e796b5b4ed.png">

[40-80] sec
<img width="844" alt="image" src="https://user-images.githubusercontent.com/3079603/56512627-d567f280-6527-11e9-99ad-15ba7f2c086d.png">

In this case, the signal gets corrupted after a few seconds but eventually, after second 30 it goes back to the correct shape.
<img width="848" alt="image" src="https://user-images.githubusercontent.com/3079603/56512746-32fc3f00-6528-11e9-81c1-98ce622f3a69.png">

Let me know your thoughts. Thanks again!

**Comment by pavel-demin** [comment]
Thanks for the new tests. So, looks like the problem is somewhere in the TX part.

While porting the SDR applications to the new 122.88-16 board, I've found that the new board is using a different pin compatible DAC chip (AD9767). The AD9767 data sheet contains some additional timing constraints. Maybe the recently produced 125-14 boards also come with the AD9767 DAC chip.

I've just backported the updated DAC interface from the code for the 122.88-16 board to the code for the 125-14 board. Here is a link to a SD card image with the updated code:

https://www.dropbox.com/sh/5fy49wae6xwxa8a/AAAn9CYl4hCq9MShSKpn2AV-a/red-pitaya-alpine-3.9-armv7-20190422.zip?dl=1

Could you please redo the first test (Exp 1) from your last comment using this new SD card image?

**Comment by fmagno** [comment]
I will double check with the oscilloscope tomorrow, but I can already say that the issue is still there by testing in closed loop:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3079603/56540384-7d99ad80-6560-11e9-8c6e-7e1bdd5d2e31.png">

50K
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/3079603/56541726-6fe62700-6564-11e9-8d55-81300e4f4279.png">


100K
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/3079603/56541467-a66f7200-6563-11e9-86bf-759c6ddf9073.png">

**Comment by fmagno** [comment]
Hi Pavel, the corruption is still there. Confirmed with the oscilloscope, especially for sample rates below 500K.

**Comment by pavel-demin** [comment]
Thanks for testing the new version. So, the problem isn't in the DAC interface.

Maybe, as a next step, we should check if the problem isn't somewhere in GNU Radio. I think that the following script is equivalent to your grc script from Exp 1:
```
import os
import struct
import socket
import numpy as np

addr = '192.168.5.100'
port = 1001

# open control socket
ctrl_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ctrl_sock.connect((addr, port))
ctrl_sock.send(struct.pack('<I', 0))

# open data socket
data_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
data_sock.connect((addr, port))
data_sock.send(struct.pack('<I', 1))

# set frequency
corr = 0
freq = 0
ctrl_sock.send(struct.pack('<I', 0<<28 | int((1.0 + 1e-6 * corr) * freq)))

# set sample rate
rates_map = {20000:0, 50000:1, 100000:2, 250000:3, 500000:4, 1250000:5}
rate = 50000
code = rates_map[rate]
ctrl_sock.send(struct.pack('<I', 1<<28 | code))

# send data
time = np.arange(0, 10, 1 / rate);
signal = np.sin(time, dtype = np.complex64)
data_sock.send(signal.tobytes())
```

**Comment by pavel-demin** [comment]
I've fixed a couple of errors in the script. I think that it should be OK now.

**Comment by fmagno** [comment]
I made a slight fix to the script (below). The OUT1 port is not producing the signal.
If I change the control and data message back to the original values, 2 and 3 respectively then I can measure at OUT1 the corrupted signal.

```import struct
import socket
import numpy as np

addr = '192.168.5.100'
port = 1001

# open control socket
ctrl_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ctrl_sock.connect((addr, port))
ctrl_sock.send(struct.pack('<I', 0))

# open data socket
data_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
data_sock.connect((addr, port))
data_sock.send(struct.pack('<I', 1))

# set frequency
corr = 0
freq = 0
ctrl_sock.send(struct.pack('<I', 0<<28 | int((1.0 + 1e-6 * corr) * freq)))

# set sample rate
rate_codes = {20000:0, 50000:1, 100000:2, 250000:3, 500000:4, 1250000:5}
rate = 50000
code = rate_codes[rate]
ctrl_sock.send(struct.pack('<I', 1<<28 | code))

# send data
# time = np.arange(0, 10, 1. / rate) * np.pi * 2
# signal = np.sin(time, dtype = np.complex64)

time = np.arange(0, 10, 1. / rate)
signal = np.sin(2 * np.pi * time, dtype = np.complex64)


data_sock.sendall(signal.tobytes())

**Comment by pavel-demin** [comment]
Yes, you're right. I've just tested the script and found more errors. Here is a new version that works for me:
```
import struct
import socket
import numpy as np

addr = '192.168.5.100'
port = 1001

# open control socket
ctrl_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ctrl_sock.connect((addr, port))
ctrl_sock.send(struct.pack('<I', 2))

# open data socket
data_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
data_sock.connect((addr, port))
data_sock.send(struct.pack('<I', 3))

# set frequency
corr = 0
freq = 0
ctrl_sock.send(struct.pack('<I', 0<<28 | int((1.0 + 1e-6 * corr) * freq)))

# set sample rate
rate_codes = {20000:0, 50000:1, 100000:2, 250000:3, 500000:4, 1250000:5}
rate = 50000
code = rate_codes[rate]
ctrl_sock.send(struct.pack('<I', 1<<28 | code))

# enable ptt
ctrl_sock.send(struct.pack('<I', 2<<28))

# send data
time = np.arange(0, 100, 1 / rate) * np.pi * 2
signal = np.sin(time, dtype = np.complex64)
data_sock.sendall(signal.tobytes())
```

**Comment by pavel-demin** [comment]
I've checked 100 periods with an oscilloscope and they all look OK. The script was running from a Ubuntu 16.04 virtual machine running under Windows 7 connected to Red Pitaya via Wi-Fi.

**Comment by fmagno** [comment]
No luck, mate... :(
I indeed see the signal coming out as I mentioned before (even if the ppt setting wasn't there before).
I also fixed the math and the division but the issue is definitely not there:

```
time = np.arange(0, 10, 1. / rate)
signal = np.sin(2 * np.pi * time, dtype = np.complex64)
```

I find it strange that it worked for you, though, because `1 / rate` should always evaluate to 0 (zero).

**Comment by fmagno** [comment]
I have also tried the [STEMlab](https://redpitaya.readthedocs.io/en/latest/quickStart/first.html) (Signal Generator) just to be sure that there is nothing wrong with hardware and it worked just fine:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/3079603/56609331-b8552180-6604-11e9-9153-5e24a0d89286.png">

**Comment by pavel-demin** [comment]
> even if the ppt setting wasn't there before

Yes, you're right. I've just checked that the script works without enabling ptt.

> I find it strange that it worked for you, though, because 1 / rate should always evaluate to 0 (zero).

I'm using Python 3:
```
# python3
Python 3.5.2
>>> 1 / 500
0.002
```

Anyway, if GNU Radio and DAC interface are OK, then the remaining parts are
- network connection
- software running on the Red Pitaya board
- FPGA configuration

I think that we could try to exclude the network connection by running the same script directly on the Red Pitaya board. I've just tried it and the following steps worked for me:
- connect to the Red Pitaya command line via SSH or via the USB/serial console
- install Python2 and NumPy
```
apk add py2-numpy
```
- edit the script and set the IP address to 127.0.0.1
- run the script
```
python2 tx.py
```

**Comment by fmagno** [comment]
> I'm using Python 3
Ah OK, my bad -  that makes sense. I assumed you were using python2 because it is not supported by GNU Radio.

Regarding the `tx.py` test here's what I got:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/3079603/56655551-044aa980-668b-11e9-9c88-c1d58f5753af.png">

The application runs for a little while, producing the output shown above and then returns without errors.
Btw, I am still using this image:
https://www.dropbox.com/sh/5fy49wae6xwxa8a/AAAn9CYl4hCq9MShSKpn2AV-a/red-pitaya-alpine-3.9-armv7-20190422.zip?dl=1

So far I have been using a cable to directly connect the redpitaya and the laptop (tried with both straight and crossover), with a static IP on both devices, to replicate the issue.

Because you suggested installing a package I had to connect the redpitaya to the internet. So, connected the redpitaya via ethernet cable to a network with internet.

The interesting part is that when I connect the computer to the same network via ethernet cable the corruption is present, but if I connect the computer to the network via WiFi I don't manifestation of the corruption for low sample rates. Also, for the 1.25M sample rate (via WiFi) the corruption looks very different IMO:

WiFi, sample rate: 20KS/s:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/3079603/56656336-28a78580-668d-11e9-8f46-2ad2230ecd74.png">

WiFi, sample rate: 1.25MS/s:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/3079603/56656360-3b21bf00-668d-11e9-9f9d-85a504776a50.png">

Ethernet, sample rate: 20KS/s:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/3079603/56656433-63a9b900-668d-11e9-8ca3-fbb06f33ef23.png">

I'm having trouble making sense of these results?

**Comment by pavel-demin** [comment]
If it works with the wireless connection and doesn't work vith the wired connection, then the problem could be in the driver of the Ethernet controller.

Looks like the Ethernet controllers based on RTL8111/8168/8411 don't work well with the drivers installed by default:
https://www.unixblogger.com/how-to-get-your-realtek-rtl8111rtl8168-working-updated-guide/

**Comment by pavel-demin** [comment]
Can we consider this issue resolved?

**Comment by fmagno** [comment]
Please keep it open. I'm currently abroad and unable to test it. I'll test it on Monday or Tuesday.

**Comment by fmagno** [comment]
Sorry, I had no chance to answer earlier because I got sick.
The good news is that I finally managed to test it with the official Realtek drivers, following your suggestion, and **IT WORKS!!**

Many thanks!

**Comment by pavel-demin** [comment]
Thanks for confirming that the problem was in the driver of the Ethernet controller.
