### ISSUE TITLE
SDR Transceiver App - Analog Input Synchronization?

### ISSUE THREAD

**Issue by alandong93** [pavel-demin/red-pitaya-notes#840]
### Description of the setup:

 * Device: STEMLab 125-14
 * SD card image: red-pitaya-alpine-3.8-armhf-20181218
 * Application: sdr-transceiver
 * Other relevant information: using GRC

### Description of the problem:

The two analog inputs do not seem to be synchronized. I tested this by connecting a waveform generator to both inputs and outputting a PWM pulse with 1 us duration. When I plot the signals from both inputs, there appears to be a time delay between samples from the two inputs. At first, I thought this would be easily compensated by adding a delay block or by offline post-processing, but the time delay changes every time I change the center frequency in GRC. The time delay also changes when I rerun the flowgraph with a different sampling rate. I have observed many different delays, such as 90 samples @ 20k samp/sec (= 4.5 ms) and 775 samples @ 500k samp/sec (= 1.5 ms). I tried many different combinations of center frequency and sampling rate and generally get between 1 and 5 ms. I tried with two different STEMLab 125-14 devices and both exhibited similar behavior. I noticed that IN1 was always ahead of IN2. Is this expected behavior?

I have attached two plots from different RPs below:

![image](https://user-images.githubusercontent.com/5303488/57172592-0f15e480-6dd7-11e9-9bd4-7ccdd2e62d8f.png)
RP#1: IN1 ahead by 362 samp @ 250 kSps (= 1.45 ms)

![image](https://user-images.githubusercontent.com/5303488/57172620-4b494500-6dd7-11e9-9727-d08b9b1ae3ce.png)
RP#2: IN1 ahead by 90 samp @ 20 kSps (= 4.5 ms)

### Steps to reproduce the problem:

 1. Run sdr-transceiver app on RP.
 2. Connect waveform generator (can also use OUT1 or OUT2 on RP) and output short pulse.
 3. Plot both signals on the same scope plot or file sink both signals and plot offline.

Thanks for all your help!

-Alan

**Comment by pavel-demin** [comment]
The analog inputs in the SDR transceiver application aren't synchronized by design. The two receivers and two transmitters are designed to be completely independent.

As a workaround, I'd suggest to try [SDR transceiver compatible with HPSDR](http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr). It has synchronized inputs and it can be used with [gr-hpsdr](https://github.com/Tom-McDermott/gr-hpsdr).
