### ISSUE TITLE
Using pulse generator

### ISSUE THREAD

**Issue by ssooffiiaannee** [pavel-demin/red-pitaya-notes#846]
### Description of the setup:

 * Device: Red Pitaya
 * SD card image: Provided by RedPitaya, this one : https://redpitaya.readthedocs.io/en/latest/quickStart/SDcard/SDcard.html
 * Application: MCPHA, pulse generator
 * Other relevant information:

### Description of the problem:
I started the mcpha application, the histogram works perfectly, but I don't know how to make the pulse generator work.

### Steps to reproduce the problem:

 1.Enter in the RP web interface.
 2.Lunch mcpha application
 3.Connect the RP to the mcpha interface,
Histograms work perfectly , but not the pulse generator, I tried to generate pulses (like the name points out) to an external oscilloscope, but no impulse is generated.

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/37119086/58241725-d1f5a000-7d4d-11e9-9186-63df626c0911.PNG">

I hope it's clear !!

**Comment by pavel-demin** [comment]
The pulse generator requires an input spectrum histogram that should be loaded using the 'Read file' button. The input spectrum histogram file should be a text file with 4096 lines with each line containing a number of entries in the corresponding histogram bin.

Here is an example of input file:
[test.zip](https://github.com/pavel-demin/red-pitaya-notes/files/3211698/test.zip)

**Comment by ssooffiiaannee** [comment]
Thanks, So I can plug the IN1 to the Out1 of the same RP, generate the impulses, and check whether we will have the same spectrum?

**Comment by pavel-demin** [comment]
Yes, it's possible to obtain more or less similar input and output spectra.

When I tested it last time, it looked like the following:

![test](https://user-images.githubusercontent.com/8037893/58256664-b26f6f00-7d6f-11e9-8d51-63970ff8b81a.png)

The input spectrum is blue, the output spectrum is black.
