### ISSUE TITLE
Using pha application

### ISSUE THREAD

**Issue by Hamam-S** [pavel-demin/red-pitaya-notes#867]
Description of the setup:
       Device: Red Pitaya 125-14
       SD card image: Image from red pitaya website
       Application: multichannel pulse height analyzer (mcpha)
       Other relevant information:

Dear Pavel,
    I'm trying to understand the purpose of the pha application (not the mcpha), it generates dat files, but I can't read them. I do not understand what the purpose of it.

I hope I gave enough information, and I'm really sorry If I missed any relevant one.

**Comment by pavel-demin** [comment]
The `pha.exe` program records timestamped pulses from both ADC channels.

The output file format is binary. Each record is 16 bytes long:

 - bytes 1-8: timestamp, 64-bit integer (uint64)
 - bytes 9-12: pulse height from IN1, 32-bit integer (int32)
 - bytes 13-16: pulse height from IN2, 32-bit integer (int32)
 
The following simple MATLAB script can read this format. I've tested it with Octave and I think that it should also work with MATLAB. 

```
fileID = fopen('pulses.dat');
data = fread(fileID, 'uint8=>uint8');
fclose(fileID);

size = [8 4 4];

data = reshape(data, sum(size), []);

temp = data(1:8, ;
time = typecast(temp(:), 'uint64');

temp = data(9:12, ;
pha1 = single(typecast(temp(:), 'int32'));

temp = data(13:16, ;
pha2 = single(typecast(temp(:), 'int32'));

pha1(pha1 == 0) = nan;
pha2(pha2 == 0) = nan;

hist(pha1, 100);

plotyy(time, pha1, time, pha2);

table = horzcat(time, pha1, pha2);
```
