### ISSUE TITLE
Red pitaya DAC issue

### ISSUE THREAD

**Issue by motagiyash** [pavel-demin/red-pitaya-notes#868]
Bonjour Mr Pavel,
 I am currently working on the project where i am working on producuing a pulse of 20 mhz frequency for 200ns, just as your Pulsed NMR project.

So for that i am using Pinc of dac and rsync to modulate the frequency and resync.

I am running DDS on 100 MHz and DAC 125 MHz.

I amm getting proper output from dds (On ILA) but when it passes through the DAC IP i gett the following result on Oscilloscope.

Could you guide me where the problem might be.

Thank you.

![qsd](https://user-images.githubusercontent.com/33543044/60009209-c6133b80-9675-11e9-87fe-3590a56dc508.png)
![unnamed (1)](https://user-images.githubusercontent.com/33543044/60009210-c6abd200-9675-11e9-9152-ec46d15f7bae.jpg)
![IMG-6479](https://user-images.githubusercontent.com/33543044/60009219-cad7ef80-9675-11e9-9437-ac4be0b22e8d.JPG)

**Comment by pavel-demin** [comment]
> Bonjour Mr Pavel,

I'm surprised to see "Mr" used in front of a given name. Is it how we use "Mr" these days in France? If you don't mind, then I'd much appreciate something simpler like "Hi Pavel".

> I am running DDS on 100 MHz and DAC 125 MHz.

For simplicity, I'd suggest to use the same clock source for all the modules.

> Could you guide me where the problem might be.

Looking at the Vivado screenshot, I'd say that the DAC interface module isn't clocked correctly. I'd suggest to use exactly the same clock sources for the DAC interface module as I use in all my projects. I think that [dac_test](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/dac_test) is the most basic project showing how to correctly use  the DAC interface module.

**Comment by motagiyash** [comment]
Thank you Mr pavel, for the help and the project work I have solved the issue buy properly modifying PINC and POFF and rsync. 

Have a good day.
