### ISSUE TITLE
Alpine image - no boot

### ISSUE THREAD

**Issue by bradman77** [pavel-demin/red-pitaya-notes#870]
### Description of the setup:

 * Device: RP 122.88-16
 * SD card image: red-pitaya-alpine-3.9-armv7-20190527.zip
 * Application: Alpine image
 * Other relevant information:

### Steps to reproduce the problem:

 1.  repartitioned sdcard, copied image red-pitaya-alpine-3.9-armv7-20190527.zip - no boot, green led only
 2.  redownloaded red-pitaya-alpine-3.9-armv7-20190527.zip, repeated step 1 - no boot, green led only
 3.  downloaded factory beta image redpitaya_OS-beta-Z20_06-jun-2019, installed via disk imager- device boots - access web interface = YES

Help please?

**Comment by pavel-demin** [comment]
> Device: RP 122.88-16

The SD card images from this repository aren't compatible with STEMlab 122.88-16 SDR.

Please use the SD card images from

https://github.com/pavel-demin/stemlab-sdr-notes/releases
