### ISSUE TITLE
Stemlab 122.88-16

### ISSUE THREAD

**Issue by dxhunter** [pavel-demin/red-pitaya-notes#871]
### Description of the setup:

 * Device:Stemlab 122.88-sdr
 * SD card image:April-2019
 * Application:wspr
 * Other relevant information:

### Description of the problem:
Wspr diversity mode causes problems at least on 40m
The log shows twice same callsigns and same signalstrength per time-slot
Thank you very much for your help
73s de Eric

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment]
> Device: Stemlab 122.88-sdr

Please move this issue to the correct repository:

https://github.com/pavel-demin/stemlab-sdr-notes

and please provide more information about your setup (hardware setup, configuration files, etc) and some log files or screenshots showing duplicated decodes.
