### ISSUE TITLE
Adc_recorder_trigger project.

### ISSUE THREAD

**Issue by z7010student** [pavel-demin/red-pitaya-notes#875]
Hi pavel,
I just started studying Red pitaya.

My objective is similar to the adc-recorder-trigger project.

but i am not able to test the project,
I generated the bitstream, loaded it up onto the FPGA.

Could you please guide me how could i test the project.(with .c and .r files)

Thank you for your help.

**Comment by pavel-demin** [comment]
After loading the bitsream file, just compile and run the C program.
