### ISSUE TITLE
Haven't found the register storing the Scope value in red_pitaya_0_92

### ISSUE THREAD

**Issue by chw177** [pavel-demin/red-pitaya-notes#876]
### Description of the setup:

 * Device: 
 * SD card image:
 * Application:
 * Other relevant information:

### Description of the problem:
Hi Pavel,

I am trying to use the project red_pitaya_0_92 to realized scope function. I connect the function generator to the adc_a to input, say, a sine wave. However, when I check the register in 0x40110000 to see the input according to line 590 in red_pitaya_0_92/red_pitaya_scope.v, I can only see 0 value. 

According to line 324, I made sure that all wen, (addr[19:0]==20'h0), and, wdata[0] are 1. They are all output to 3 distinct LEDs and they all light up. So that I believe that adc_arm_do is 1. However I still cannot see the stored value of adc_a and adc_b. (Sporadically some very small nonzero number appears but more like noise.)

Would you please give me a brief suggestion about how to realize this scope function and in which register to check the input adc_a and adc_b value?

Thank you very much,
Chen Wu

### Steps to reproduce the problem:

 1. Based on original red_pitaya_0_92, in the top file, add reg w_enable = 1'b1.
 2. assign sys_wen[1] = w_enable
 3. Write bitstream and implement on the redpitaya.
 4. monitor 0x40100000 0x0001
 5. monitor 0x40110000 
 6. Only can see 0x00000000 (Sporadically some very small nonzero number appears but more like noise.)

**Comment by pavel-demin** [comment]
I'm afraid that I can't help you with this issue.

I'm not the author of the red_pitaya_0_92 code. It's a copy of an old version of the Red Pitaya code with a few minor changes to make it compatible with the names of the ports that I use in my other projects. The original code can be found in the Red Pitaya repository:

https://github.com/RedPitaya/RedPitaya/tree/0.92/FPGA/release1/fpga/code/rtl

Last time I tested it, my copy of the code worked with the Oscilloscope application. So, I think that I didn't break it too much when copied.
