### ISSUE TITLE
FT4

### ISSUE THREAD

**Issue by jeffforber** [pavel-demin/red-pitaya-notes#879]
### Description of the setup:

 * Device:
 * SD card image:
 * Application:
 * Other relevant information:

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by jeffforber** [comment]
hi Pavel .....is there any chance of a FT4 tranceiver

**Comment by pavel-demin** [comment]
I think that there are some chances. They would be higher if you contribute.
