### ISSUE TITLE
Differential I-Q Signal generation possibility from wideband sdr.

### ISSUE THREAD

**Issue by uiuatiq** [pavel-demin/red-pitaya-notes#884]

**Comment by pavel-demin** [comment]
Without any details in the description, I don't really understand what is the problem.

I can only suggest to have a look at the "Transmitting and receiving complex baseband signals" section in my notes about the wideband SDR transceiver at the following link:
http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-wide/#transmitting-and-receiving-complex-baseband-signals

It shows how the GNU Radio blocks can be configured to transmit and to receive complex baseband signals via two outputs (OUT1 and OUT2) and two inputs (IN1 and IN2),
