### ISSUE TITLE
Reg simulating and understanding the IP cores

### ISSUE THREAD

**Issue by falcon98** [pavel-demin/red-pitaya-notes#885]
Dear Pavel,

Thanks for the great work. 

I had a doubt I wanted to develop better understanding of the RP projects. Though I am able to read the code and develop some understanding, I wanted to test some important IP cores such as Oscilloscope, Trigger and ADC IPs.
I wanted your suggestion in this regard. Is it sufficient to simulate each IP core in single project to understand the functioning. 
Is the simulation of IP cores a big task in itself . Are the efforts worth their time.

I apologize if this is a stupid question but I had this in my mind since major IPs are prepared by you.

Best regards,
David

**Comment by pavel-demin** [comment]
> Is it sufficient to simulate each IP core in single project to understand the functioning.

I think that it can be done. There are *_test projects in this repository that I use for testing some of the IP cores.

> Is the simulation of IP cores a big task in itself. Are the efforts worth their time.

Can't answer these questions. I don't use the simulation with my IP cores.
