### ISSUE TITLE
decimation and transmit it back to PC

### ISSUE THREAD

**Issue by motagiyash** [pavel-demin/red-pitaya-notes#888]
Hello Pavel,

Hope your doing well,

I am working on the project where i need to perform decimation of the signal from ADC and send the decimated data to PC.

I was going through your projects, I think SDR reciver resembles more to it or ADC recorder trigger.

Thank you in advance for your help.

**Comment by pavel-demin** [comment]
I think that the most basic project that has this functionality is [adc_test](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/adc_test).
