### ISSUE TITLE
Dought in SDR_reciver decoding

### ISSUE THREAD

**Issue by motagiyash** [pavel-demin/red-pitaya-notes#890]
Hi Pavel,

Thanks for al the work.

Right now i am working on the bare metal application of you SDR_reciver project.

I do have a setup where i  am reciving I and Q at 2 of the ADC inputs. Could you please tell me why is cordic algo used for.

I will be using your same setup of CIC and FIR filters.

I also have implemented the ethernet application.

Just stuck at this point, I am unable to understand the cordic algorithm and why perticular phase value is use as a input. 

`    /* set default phase increment */
    *((uint32_t *)(cfg + 4)) = (uint32_t)floor(600000/125.0e6*(1<<30)+0.5); `

Thank you and looking forward to hearing from you.

Yash

**Comment by pavel-demin** [comment]
> Could you please tell me why is cordic algo used for.

I am afraid I don't understand this question. Do you mean "why cordic is used" or "what for cordic is used"?

In any case, this project implements the most basic quadrature demodulator. So, if anything isn't clear, just have a look at some articles about quadrature  demodulators and CORDIC.

> why perticular phase value is use as a input.
> `floor(600000/125.0e6*(1<<30)+0.5)`

The default center frequency is set to 600 kHz without any particular reason. The 600 kHz value is converted to a 30-bit phase increment that is used by a phase counter running at 125 MHz.

**Comment by motagiyash** [comment]
Thank you pavel

and also at the output of stream combiner you have 64 bits and at the input of fir its configured 32 bit input.
![Screenshot from 2019-10-24 14-06-48](https://user-images.githubusercontent.com/33543044/67484383-53888b80-f668-11e9-9509-f4b7c78996f7.png)

**Comment by pavel-demin** [comment]
> input of fir its configured 32 bit input

It's not what your screenshot shows. On the screenshot, I see that the combiner output and FIR input are both 64-bit.

Please consider looking for answers in the Xilinx documentation and other sources on the web. I'm really not interested in explaining all the minutiae details of my code. Everything I'm interested in sharing is already in this GitHub repository and in the notes.

The SDR receiver is the very first SDR project that I implemented. So, it's very simple and it's based on the information that I found on the web and in the Xilinx documentation. You can find some links in the very beginning of my [SDR receiver notes](http://pavel-demin.github.io/red-pitaya-notes/sdr-receiver/#interesting-links).
