### ISSUE TITLE
Updated GNURadio modules to use yaml , see my repository

### ISSUE THREAD

**Issue by AB4EJ-1** [pavel-demin/red-pitaya-notes#899]
FYI, I created the yml files so that the Red Pitaya GNURadio OOT modules (source and sink) will work with the latest GNURadio (version 3.8). See here: https://github.com/AB4EJ-1/red-pitaya-notes/tree/master/projects/sdr_transceiver/gnuradio
I have tested the source module (it works). The sink module gives no errors in the GRC, but I don't know whether it actually turns on the signal generator when ptt button clicked.

I'm sure there is a better way to submit this for your consideration, but I am just learning git, so this is my attempt to make a contribution.

**Comment by pavel-demin** [comment]
Thank you for the YAML files.

I've set the PTT type to int in the sink blocks and reformatted the make function call. I've also added the YAML files to the wideband SDR transceiver.

The YAML files are added to this repository with [this pull request](https://github.com/pavel-demin/red-pitaya-notes/pull/915).
