### ISSUE TITLE
Establish ssh connection on default debian image

### ISSUE THREAD

**Issue by iAnyKey** [pavel-demin/red-pitaya-notes#910]
Hi @pavel-demin ,

Sorry for probably a trivial question, but I simply do not have enough experience yet.
I have successfully built led_blinker project from this repository.
Red-Pitaya boots and LED0 flashes just as it has to. 

I'm trying to connect to my Red-Pitaya over ssh right now and it sadly noesnt work yet.
Setup:
   * wired ethernet connection to RP from windows 10 PC with automatic assigned IP address.
   * no modifications on linux image

Regardind to contains of `/etc/hostname` and `etc/network/interfaces.d/eth0` on RedPitaya-Debian you provided, I suppose, that RP has a hostname `red-pitaya` and receives IP dynamically from dhcp. So I should be able to ping or setup a ssh-connection to `red-pitaya` or `red-pitaya.local` just after I plug in the ethernet cable.
Unfortunately I cannot reach the host.
Do you have a hint for me?

Regards,
Dimitrii

**Comment by pavel-demin** [comment]
If you use the SD card image based on the Debian Linux distribution, then this SD card image only has the most basic features. It does not have mDNS/DNS-SD. So, you must specify the IP address of the Red Pitaya board to open an SSH connection.

I do not actively develop the SD card image based on the Debian Linux distribution. I only keep it and maintain it for historical reasons.

If you use the SD card image based on the Alpine Linux distribution, then it has mDNS/DNS-SD and it can be accessed as `rp-f0xxxx.local`, where `f0xxxx` are the last 6 characters from the MAC address written on the Ethernet connector.

You can find some information about the network configuration in the "Network configuration" section of my notes about the SD card image based on the Alpine Linux distribution:

http://pavel-demin.github.io/red-pitaya-notes/alpine/#network-configuration
