### ISSUE TITLE
very wideband DDC/s

### ISSUE THREAD

**Issue by johnretired** [pavel-demin/red-pitaya-notes#921]
Can the STEMlab 122.88-16 SDR support TWO wideband DDC/s with a 6.144 MHz bandwidth each?  I don't need any DUC/s implemented on the device.

**Comment by pavel-demin** [comment]
If 16-bit I and Q values are OK for your project, then I think that it's possible. The bottleneck is the network bandwidth.

The correct repository for STEMlab 122.88-16 SDR related code and issues is
https://github.com/pavel-demin/stemlab-sdr-notes
