### ISSUE TITLE
  Please Teach me how CIC and fir match

### ISSUE THREAD

**Issue by gongcsf** [pavel-demin/red-pitaya-notes#932]
the SDR transceiver 

CIC out is 50-3125 Decimation  

fir  Input Sampling Frequency is 2.5 Mhz  When CIC changes the Decimation rate 

fir How to match

Please teach me.

I am a novice. and ,Can't speak English 
![2020-02-09 ](https://user-images.githubusercontent.com/3991934/74097122-7ff6e380-4b43-11ea-8368-ddb9eab3b03b.jpg)
[https://user-images.githubusercontent.com/3991934/74097144-b2084580-4b43-11ea-9cf3-716deaf798da.jpg](url)

**Comment by gongcsf** [comment]
[https://raw.githubusercontent.com/gongcsf/test/master/2020-02-09%20.jpg](url)

**Comment by pavel-demin** [comment]
Here is a link to Intel/Altera application note 455 on CIC filters:
https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/an/an455.pdf

The frequency response of the CIC filter doesn't change much with decimation rate (see Figure 10b in [this article](https://www.embedded.com/understanding-cascaded-integrator-comb-filters)). So, the same FIR filter can be used for all decimation rates.
