### ISSUE TITLE
16-bit Data to store in RAM.

### ISSUE THREAD

**Issue by 117-byte** [pavel-demin/red-pitaya-notes#937]
### Description of the setup:

 * Device: Red Pitaya
 * SD card image:
 * Application: Xilinx - Vivado 
 * Other relevant information:

### Description of the problem:
Hi Everyone/sir , 
I'm following your **Red-pitaya notes code** for my project  work. And currently working on ADC, so the thing is i want to use (Access) **16-bit data** through RAM, by using 3 IP's (AXI- stream packetizer, AXI Stream data width converter , and AXI - RAM writer in ADC- RECORDER) Please suggest me which is the right path for this ? Currently i'm doing this by changing the width of these three IP. 
Thanks in Advance  :). 

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment]
From the description of your project it is not clear why something should be changed. I think it would be enough to read the required 16 bits in the C code and ignore the remaining 16 bits.
