### ISSUE TITLE
Red Pitaya-VNA tcl file in vivado

### ISSUE THREAD

**Issue by 117-byte** [pavel-demin/red-pitaya-notes#940]
### Description of the problem:
Hii, 
As you suggest me in my previous post to use VNA project from your  repository. 

I tried looking at the block diagram of your vna of the stemlab_vna which I assume is the: block_design.tlc located in: \red-pitaya-notes-master\apps-free\stemlab_vna

However if I try to run it in vivado 2018.2 via source block_design.tcl it get an error: 

`invalid command name "cell"
    while executing
"cell xilinx.com:ip:clk_wiz:5.3 pll_0 {
  PRIMITIVE PLL
  PRIM_IN_FREQ.VALUE_SRC USER
  PRIM_IN_FREQ 125.0
  PRIM_SOURCE Differential_clock_capable_pin..."
    (file "block_design.tcl" line 2)`

I already looked at your thread No. #814 and #718 

but vna doesn't have any build - core file as you suggest them as a solution.

**Comment by pavel-demin** [comment]
It seems that in the previous issue that you opened I did not manage to explain to you clearly that I am not going to help you with the problems which you meet when you modify my code or use code coming from other repositories. It is up to you to fix the bugs that you introduce when modifying my code.

Before writing your next comment on this issue or before opening a new issue in this repository, please read the following tips and try to apply them in practice:
https://www.tomasvotruba.com/blog/2019/07/08/7-tips-to-write-flawless-issue-report-on-github/

> However if I try to run it in vivado 2018.2 via source block_design.tcl it get an error:

The build commands for the vna project are exactly the same as for the adc_recorder project. So, if you managed to build the adc_recorder project, then I don't understand why you have problems with the vna projects.

Moreover, some examples of build commands can be found in the corresponding section of the notes:
http://pavel-demin.github.io/red-pitaya-notes/vna/#building-from-source

I'm currently using Vitis/Vivado 2019.2 to build my projects. So, if you want to reproduce my builds, I'd suggest to use Vitis/Vivado 2019.2.

More information about my workflow and about the structure of this repository can be found in the LED blinker notes and in the slides of my presentation at Club Vivado 2016:
http://pavel-demin.github.io/red-pitaya-notes/led-blinker/
https://www.dropbox.com/sh/5fy49wae6xwxa8a/AACl--BhQvcNgjeQLRaiX9dha/ClubVivado2016_Pavel_Demin.pdf?dl=1

> I tried looking at the block diagram of your vna of the stemlab_vna which I assume is the: block_design.tlc located in: \red-pitaya-notes-master\apps-free\stemlab_vna

This doesn't look like a directory from this repository. There is no apps-free directory in this repository.

Here are the correct links to the code and to the notes:
https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/vna/
http://pavel-demin.github.io/red-pitaya-notes/vna/
