### ISSUE TITLE
 How to use GNU radio to successful connect the Red Pitaya?

### ISSUE THREAD

**Issue by friedrich1993322** [pavel-demin/red-pitaya-notes#965]
I installed your official APP "SDR transceiver". But when I run your example program, the program told me "socket.error: [Errno 111] Connection refused" (shown in Figure 1) The IP address is right (shown in Figure 2). Could you tell me, where is wrong. And how to modify it? 

### Description of the setup:

 * Device:Red Pitaya
 * SD card image:
 * Application:SDR transceiver
 * Other relevant information:

### Steps to reproduce the problem:

 1. install SDR transceiver
 2.run the example programm
 3.

**Comment by pavel-demin** [comment]
Unfortunately, I do not see figures 1 and 2. It seems that there was a problem with attaching them to your comment.

I'd say that one step is missing in your list:
1. install SDR transceiver
2. run SDR transceiver
3. run the example program

Please check if the SDR transceiver application is running on the Red Pitaya board.

**Comment by pavel-demin** [comment]
I received the screenshots by e-mail.

The port parameter of the Red Pitaya Source block is set to an incorrect value (5k).

The correct value for the port parameter is 1001.
