### ISSUE TITLE
Different RX Sample Rates SDR-Transceiver-HPSDR

### ISSUE THREAD

**Issue by Fiete953** [pavel-demin/red-pitaya-notes#974]
Hi Pavel,

I try to use RX1 and RX2 with different sample rates. 

The AX4 stream variable rate_0 ... rate_7 that control the CICs are connected in parallel at their cfg_data inputs.

Do I have to do more than supply rx_0/rate_2/cfg_data and rx_0/rate_3/cfg_data with the factor for RX2 and the remaining 6 rx_0/rate_x/cfg_data with the factor for RX1?

Thanks for giving me a hint!

**Comment by pavel-demin** [comment]
The HPSDR/Metis communication protocol doesn't support different sample rates on different receivers. So the sdr_transceiver_hpsdr project doesn't support this either. You'll need to do more than just change  rx_0/rate_2/cfg_data and rx_0/rate_3/cfg_data. You'll need to rearrange the RX part in both FPGA and C code. I think the easiest way would be to make two copies of rx.tcl with different numbers of receivers.
