### ISSUE TITLE
Lag in Red Pitaya output voltage response time

### ISSUE THREAD

**Issue by TestingAccount4** [pavel-demin/red-pitaya-notes#990]
### Description of the setup:

 * Device: Red Pitaya Stemlab 125-14
 * SD card image: 0.98-696
 * Application: Custom (see attached), modified Frequency counter project from Anton

 
### Description of the problem:
Eventually, I am looking to output a voltage from a look up table stored in memory depending on if a specific signal was detected in a user specified window. To test basic functionality, I modified Anton's project to create a project that outputs +1 V when the input signal is positive, and -1 V when the input signal is negative. The RP was able to detect and adjust accordingly, but there is approximately 100 ns of delay between the input signal changing sign and the RP responding, not counting the time it takes for the output voltage to ramp up to + or - 1V (see screenshot below). I'd like to minimize this lag in response time as much as possible. I looked into Pavel's cores Anton uses in this project, and I think it may have something to do with the ODDR block, but I'm not sure what causes this and how to change it.

Here is a screen grab of an oscilloscope illustrating the issue. The green signal is the input, and the purple signal is the RP output.

![Binary LUT Oscilloscope](https://user-images.githubusercontent.com/37088355/102249439-9ab28b00-3ebf-11eb-95db-44bb15c9ab25.jpg)

The code for my binary lookup table is below. The rest is Anton's frequency counter project modified as shown. 

```
`timescale 1ns / 1ps

module binary_lookup_table(
    input wire clk,
    input wire signed [15:0] SNSPD_sig,
    input wire [31:0] temp_1,
    input wire [31:0] temp_2,
   
    
    output reg [15:0] amplitude_voltage,
    output reg [15:0] phase_voltage
    );
    
    
   
    //Defining a set of registers to hold the signals.
    reg [15:0] input_data_photon_detection_1=16'sd0;
    reg [15:0] input_data_photon_detection_2=16'sd0;
 
  
    
    always@(posedge clk) begin
   
         
        input_data_photon_detection_1<=input_data_photon_detection_2;
        input_data_photon_detection_2<=SNSPD_sig;
        

        if(1>0) begin
   
            //Output threshold detection. If the input voltage is greater than 0 V output +1 V. If it is below 0 V output -1 V.
            if((input_data_photon_detection_2>16'sd0)) begin  
                amplitude_voltage<=16'sd8191;     
            end else begin
                amplitude_voltage<=-16'sd8192;
            end  
            
         phase_voltage<=16'sd0;
 

            end
  
    end
endmodule
```

![Binary Lookup Table 1](https://user-images.githubusercontent.com/37088355/102248296-44911800-3ebe-11eb-8990-243d513f8c58.PNG)

![Binary Lookup Table 2](https://user-images.githubusercontent.com/37088355/102248375-58d51500-3ebe-11eb-8fd1-0a6912468d22.PNG)

![Binary Lookup Table 3](https://user-images.githubusercontent.com/37088355/102248426-64284080-3ebe-11eb-990b-3e216c9a67c3.PNG)

### Steps to reproduce the problem:

 1. Configure Anton's fourth project as described on his website and make the necessary edits to match the project I have above. Generate and deploy the bitstream.
 2. Attach a square wave with a frequency <45 MHz (around 5 MHz works well to demonstrate the lag time) to the RP in input port 1, and attach output port 1 to an oscilloscope.

**Comment by pavel-demin** [comment]
> there is approximately 100 ns of delay between the input signal changing sign and the RP responding
> I think it may have something to do with the ODDR block,

The 100 ns delay is certainly not from the ODDR block. I don't think the ODDR block is delaying the signal by more than 8 ns.

It takes some time for ADC and DAC chips to perform AD and DA conversions. I won't be surprised if this time is around a few tens of nanonseconds. In addition, each register in the path from the ADC to DAC introduces an 8 ns delay.

The binary_lookup_table module delays the signal by 16 ns. The axis_red_pitaya_adc modules delays the signal by 8 ns. The axis_red_pitaya_dac modules delays the signal by 16 ns. Together these three modules delay the signal by 40 ns.

So, I think the 100ns delay is perfectly normal and expected from the components used on the Red Pitaya board.
