### ISSUE TITLE
multi band wspr transceiver

### ISSUE THREAD

**Issue by jeffforber** [pavel-demin/red-pitaya-notes#998]
using the the multi band wspr t/r ...i configured the tx message "TA4/G8SCU KM56 10" it works great except the power reported on WSPRNET is 0.001W   i tried different power settings ie 30dbm etc but WSPRnet still reports 0.001W ...please can you advise  
regards Jeff 

### Description of the setup:

 * Device: rp 14 125
 * SD card image: red-pitaya-alpine-3.12-armv7-20200628

**Comment by jeffforber** [comment]
using multi band wspr t/r i configure tx message "TA4/G8SCU KM56 10" its running good lots of spots with only 10mw ..but WSPRnet is reporting power as 0.001W changing the power on tx message doesnt make any difference ie   33dbm still reports as 0.001W  please advise regards jeff TA4/G8SCU

**Comment by pavel-demin** [comment]
Looks like a problem with the format of your message. A description of three types of WSPR messages can be found at [this link](https://dxplorer.net/wspr/msgtypes.html).

Since you are using a compound callsign (with a slash), the correct format is "TA4/G8SCU 10".

**Comment by pavel-demin** [comment]
BTW. I only tested the transmission of the type 1 messages (without slash). I didn't know about other formats.
